### ISSUE TITLE
Crash when visiting moon (something with render)

### ISSUE THREAD

**Issue by dillasyx** [BlesseNtumble/GalaxySpace#102]
Everytime I travel to moon, the game crashes, no problems in other dimensions

`java.lang.NoSuchFieldError: overworldTexturesValid
    at galaxyspace.SolarSystem.moons.moon.dimension.sky.SkyProviderMoon.render(SkyProviderMoon.java:270)
    at net.minecraft.client.renderer.RenderGlobal.func_72714_a(RenderGlobal.java:964)
    at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1167)
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1015)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)`

here is the whole log:
[crash-2016-10-19_22.52.12-client.txt](https://github.com/BlesseNtumble/GalaxySpace/files/540165/crash-2016-10-19_22.52.12-client.txt)

**Comment by BlesseNtumble** [comment]
Version GC3?

**Comment by dillasyx** [comment]
I think it's 1.7-3.0.12.463, will have a look later at home.

**Comment by BlesseNtumble** [comment]
Well....
(GalacticraftCore-1.7-3.0.12.440.jar) 

Update GC3.
