### ISSUE TITLE
Опять что-то не так...

### ISSUE THREAD

**Issue by kebabmamedov** [BlesseNtumble/GalaxySpace#118]
Создаю в мир, и вот такая *****:

---- Minecraft Crash Report ----
// On the bright side, I bought you a teddy bear!

Time: 12.11.16 19:12
Description: Unexpected error

java.lang.IndexOutOfBoundsException
	at java.nio.Buffer.checkIndex(Buffer.java:540)
	at java.nio.DirectIntBufferU.get(DirectIntBufferU.java:253)
	at net.minecraft.client.renderer.RenderGlobal.func_72712_a(RenderGlobal.java:350)
	at net.minecraft.client.renderer.RenderGlobal.func_72732_a(RenderGlobal.java:294)
	at net.minecraft.client.Minecraft.func_71353_a(Minecraft.java:2216)
	at net.minecraft.client.Minecraft.func_71403_a(Minecraft.java:2146)
	at net.minecraft.client.network.NetHandlerPlayClient.func_147282_a(NetHandlerPlayClient.java:240)
	at com.mumfrey.liteloader.client.PacketEventsClient.handlePacket(PacketEventsClient.java:106)
	at com.mumfrey.liteloader.core.PacketEvents.handlePacketEvent(PacketEvents.java:179)
	at com.mumfrey.liteloader.core.PacketEvents.handlePacket(PacketEvents.java:134)
	at com.mumfrey.liteloader.core.PacketEvents.handlePacket(PacketEvents.java:129)
	at com.mumfrey.liteloader.core.event.EventProxy$2.$event00025(Unknown Source)
	at net.minecraft.network.play.server.S01PacketJoinGame.func_148833_a(SourceFile)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2061)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at java.nio.Buffer.checkIndex(Buffer.java:540)
	at java.nio.DirectIntBufferU.get(DirectIntBufferU.java:253)
	at net.minecraft.client.renderer.RenderGlobal.func_72712_a(RenderGlobal.java:350)
	at net.minecraft.client.renderer.RenderGlobal.func_72732_a(RenderGlobal.java:294)
	at net.minecraft.client.Minecraft.func_71353_a(Minecraft.java:2216)
	at net.minecraft.client.Minecraft.func_71403_a(Minecraft.java:2146)
	at net.minecraft.client.network.NetHandlerPlayClient.func_147282_a(NetHandlerPlayClient.java:240)
	at com.mumfrey.liteloader.client.PacketEventsClient.handlePacket(PacketEventsClient.java:106)
	at com.mumfrey.liteloader.core.PacketEvents.handlePacketEvent(PacketEvents.java:179)
	at com.mumfrey.liteloader.core.PacketEvents.handlePacket(PacketEvents.java:134)
	at com.mumfrey.liteloader.core.PacketEvents.handlePacket(PacketEvents.java:129)
	at com.mumfrey.liteloader.core.event.EventProxy$2.$event00025(Unknown Source)
	at net.minecraft.network.play.server.S01PacketJoinGame.func_148833_a(SourceFile)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)

-- Affected level --
Details:
	Level name: MpServer
	All players: 0 total; []
	Chunk stats: MultiplayerChunkCache: 0, 0
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 0 total; []
	Retry entities: 0 total; []
	Server brand: ~~ERROR~~ NullPointerException: null
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:927)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Mac OS X (x86_64) version 10.12.2
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 175075200 bytes (166 MB) / 467750912 bytes (446 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 5 total; -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 1, tcache: 29, allocated: 2, tallocated: 28
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1558 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1558-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1558} [Minecraft Forge] (forge-1.7.10-10.13.4.1558-1.7.10.jar) 
	UCHIJAAAA	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
	UCHIJAAAA	GalacticraftCore{3.0.12} [Galacticraft Core] (GalacticraftCore-1.7-3.0.12.463.jar) 
	UCHIJAAAA	GalacticraftMars{3.0.12} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.12.463.jar) 
	UCHIJAAAA	GalaxySpace{1.1.2} [GalaxySpace] (GalaxySpace-1.1.2 STABLE.jar) 
	GL info: ' Vendor: 'Intel Inc.' Version: '2.1 INTEL-10.22.17' Renderer: 'Intel Iris OpenGL Engine'
	Launched Version: 1.7.10
	LWJGL: 2.9.1
	OpenGL: Intel Iris OpenGL Engine GL version 2.1 INTEL-10.22.17, Intel Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: Русский (Россия)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by BlesseNtumble** [comment]
Откуда я знаю?
Какой-то мод на liteloader крашит.

Хватит создавать темы не по аддону. Первое и последнее предупреждение.

**Comment by kebabmamedov** [comment]
Когда у меня крашится майн со сборкой где есть Galacticraft и GalaxySpace, я обращаюсь сюда

**Comment by kebabmamedov** [comment]
И вообще, у меня нету модов на LiteLoader
<img width="977" alt="2016-11-13 11 53 38" src="https://cloud.githubusercontent.com/assets/14090079/20244549/07d6278a-a998-11e6-9a8d-5d1da28efedc.png">

**Comment by BlesseNtumble** [comment]
at com.mumfrey.liteloader.client.PacketEventsClient.handlePacket(PacketEventsClient.java:106)
at com.mumfrey.liteloader.core.PacketEvents.handlePacketEvent(PacketEvents.java:179)
at com.mumfrey.liteloader.core.PacketEvents.handlePacket(PacketEvents.java:134)
at com.mumfrey.liteloader.core.PacketEvents.handlePacket(PacketEvents.java:129)
at com.mumfrey.liteloader.core.event.EventProxy$2.$event00025(Unknown Source)

Это что? Это ошибки LiteLoader
