### ISSUE TITLE
Вылетает при приземлении на центавру b!

### ISSUE THREAD

**Issue by KontranRUS** [BlesseNtumble/GalaxySpace#119]
При приземлении на центавру b игра вылетает! Крашлог:
---- Minecraft Crash Report ----
// Sorry :(

Time: 11/13/16 2:51 AM
Description: Ticking player

java.lang.NullPointerException: Ticking player
	at galaxyspace.SolarSystem.planets.overworld.items.ItemArmors.gravityOverrideIfLow(ItemArmors.java:102)
	at micdoodle8.mods.galacticraft.core.util.WorldUtil.getGravityForEntity(WorldUtil.java:124)
	at net.minecraft.entity.EntityLivingBase.func_70612_e(EntityLivingBase.java:1510)
	at net.minecraft.entity.player.EntityPlayer.func_70612_e(EntityPlayer.java:1656)
	at net.minecraft.entity.player.EntityPlayerMP.localMoveEntityWithHeading(EntityPlayerMP.java)
	at api.player.server.ServerPlayerAPI.moveEntityWithHeading(Unknown Source)
	at net.minecraft.entity.player.EntityPlayerMP.func_70612_e(EntityPlayerMP.java)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:1814)
	at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:540)
	at net.minecraft.entity.player.EntityPlayerMP.localOnLivingUpdate(EntityPlayerMP.java)
	at api.player.server.ServerPlayerAPI.onLivingUpdate(Unknown Source)
	at net.minecraft.entity.player.EntityPlayerMP.func_70636_d(EntityPlayerMP.java)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1611)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:288)
	at net.minecraft.entity.player.EntityPlayerMP.localOnUpdateEntity(EntityPlayerMP.java:295)
	at api.player.server.ServerPlayerAPI.onUpdateEntity(Unknown Source)
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java)
	at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:224)
	at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:137)
	at net.minecraft.network.play.client.C03PacketPlayer$C06PacketPlayerPosLook.func_148833_a(SourceFile:20)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at galaxyspace.SolarSystem.planets.overworld.items.ItemArmors.gravityOverrideIfLow(ItemArmors.java:102)
	at micdoodle8.mods.galacticraft.core.util.WorldUtil.getGravityForEntity(WorldUtil.java:124)
	at net.minecraft.entity.EntityLivingBase.func_70612_e(EntityLivingBase.java:1510)
	at net.minecraft.entity.player.EntityPlayer.func_70612_e(EntityPlayer.java:1656)
	at net.minecraft.entity.player.EntityPlayerMP.localMoveEntityWithHeading(EntityPlayerMP.java)
	at api.player.server.ServerPlayerAPI.moveEntityWithHeading(Unknown Source)
	at net.minecraft.entity.player.EntityPlayerMP.func_70612_e(EntityPlayerMP.java)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:1814)
	at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:540)
	at net.minecraft.entity.player.EntityPlayerMP.localOnLivingUpdate(EntityPlayerMP.java)
	at api.player.server.ServerPlayerAPI.onLivingUpdate(Unknown Source)
	at net.minecraft.entity.player.EntityPlayerMP.func_70636_d(EntityPlayerMP.java)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1611)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:288)

-- Player being ticked --
Details:
	Entity Type: null (net.minecraft.entity.player.EntityPlayerMP)
	Entity ID: 462
	Entity Name: KontranRUS
	Entity's Exact location: 355.50, 899.60, 379.50
	Entity's Block location: World: (355,899,379), Chunk: (at 3,56,11 in 22,23; contains blocks 352,0,368 to 367,255,383), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, 0.00, 0.00
Stacktrace:
	at net.minecraft.entity.player.EntityPlayerMP.localOnUpdateEntity(EntityPlayerMP.java:295)
	at api.player.server.ServerPlayerAPI.onUpdateEntity(Unknown Source)
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java)
	at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:224)
	at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:137)
	at net.minecraft.network.play.client.C03PacketPlayer$C06PacketPlayerPosLook.func_148833_a(SourceFile:20)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@1e43bfcc
Stacktrace:
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_111, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1821417320 bytes (1737 MB) / 2432172032 bytes (2319 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms1024m -Xmx4096m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 7, tcache: 0, allocated: 15, tallocated: 95
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 66 mods loaded, 66 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10-universal.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10-universal.jar) 
	UCHIJAAAA	appliedenergistics2-core{rv3-beta-6} [Applied Energistics 2 Core] (minecraft.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
	UCHIJAAAA	PlayerAPI{1.4} [Player API] (minecraft.jar) 
	UCHIJAAAA	OpenModsCore{0.9.1} [OpenModsCore] (minecraft.jar) 
	UCHIJAAAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJAAAA	appliedenergistics2{rv3-beta-6} [Applied Energistics 2] (appliedenergistics2-rv3-beta-6.jar) 
	UCHIJAAAA	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UCHIJAAAA	BiblioCraft{1.11.5} [BiblioCraft] (BiblioCraft[v1.11.5][MC1.7.10].jar) 
	UCHIJAAAA	CoFHCore{1.7.10R3.1.3} [CoFH Core] (CoFHCore-[1.7.10]3.1.3-327.jar) 
	UCHIJAAAA	ThermalFoundation{1.7.10R1.2.5} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.2.5-115.jar) 
	UCHIJAAAA	ThermalExpansion{1.7.10R4.1.4} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.1.4-247.jar) 
	UCHIJAAAA	BigReactors{0.4.3A} [Big Reactors] (BigReactors-0.4.3A.jar) 
	UCHIJAAAA	BuildCraft|Core{7.1.18} [BuildCraft] (buildcraft-7.1.18.jar) 
	UCHIJAAAA	BuildCraft|Transport{7.1.18} [BC Transport] (buildcraft-7.1.18.jar) 
	UCHIJAAAA	BuildCraft|Silicon{7.1.18} [BC Silicon] (buildcraft-7.1.18.jar) 
	UCHIJAAAA	BuildCraft|Energy{7.1.18} [BC Energy] (buildcraft-7.1.18.jar) 
	UCHIJAAAA	BuildCraft|Factory{7.1.18} [BC Factory] (buildcraft-7.1.18.jar) 
	UCHIJAAAA	BuildCraft|Builders{7.1.18} [BC Builders] (buildcraft-7.1.18.jar) 
	UCHIJAAAA	BuildCraft|Robotics{7.1.18} [BC Robotics] (buildcraft-7.1.18.jar) 
	UCHIJAAAA	Forestry{4.2.12.60} [Forestry for Minecraft] (forestry_1.7.10-4.2.12.60.jar) 
	UCHIJAAAA	BuildCraft|Compat{7.1.5} [BuildCraft Compat] (buildcraft-compat-7.1.5.jar) 
	UCHIJAAAA	Railcraft{9.8.0.0} [Railcraft] (Railcraft_1.7.10-9.8.0.0.jar) 
	UCHIJAAAA	ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJAAAA	chisel{2.9.5.11} [Chisel] (Chisel-2.9.5.11.jar) 
	UCHIJAAAA	CarpentersBlocks{3.3.8.1} [Carpenter's Blocks] (Carpenter's Blocks v3.3.8.1 - MC 1.7.10.jar) 
	UCHIJAAAA	ChestTransporter{2.0.6} [Chest Transporter] (ChestTransporter-1.7.10-2.0.6.jar) 
	UCHIJAAAA	DynamicLights{1.3.5} [Dynamic Lights] (DynamicLights-1.7.10.jar) 
	UCHIJAAAA	DynamicLights_onFire{1.0.4} [Dynamic Lights Burning Entity Module] (DynamicLights-1.7.10.jar) 
	UCHIJAAAA	DynamicLights_creepers{1.0.4} [Dynamic Lights Creeper Module] (DynamicLights-1.7.10.jar) 
	UCHIJAAAA	DynamicLights_dropItems{1.0.7} [Dynamic Lights EntityItem Module] (DynamicLights-1.7.10.jar) 
	UCHIJAAAA	DynamicLights_entityClasses{1.0.1} [Dynamic Lights Entity Light Module] (DynamicLights-1.7.10.jar) 
	UCHIJAAAA	DynamicLights_mobEquipment{1.0.5} [Dynamic Lights Mob Equipment Light Module] (DynamicLights-1.7.10.jar) 
	UCHIJAAAA	DynamicLights_flameArrows{1.0.0} [Dynamic Lights Fiery Arrows Light Module] (DynamicLights-1.7.10.jar) 
	UCHIJAAAA	DynamicLights_floodLights{1.0.1} [Dynamic Lights Flood Light] (DynamicLights-1.7.10.jar) 
	UCHIJAAAA	DynamicLights_otherPlayers{1.0.7} [Dynamic Lights OtherPlayers Light Module] (DynamicLights-1.7.10.jar) 
	UCHIJAAAA	DynamicLights_thePlayer{1.1.3} [Dynamic Lights Player Light Module] (DynamicLights-1.7.10.jar) 
	UCHIJAAAA	eplus{3.0.2-d} [Enchanting Plus] (EnchantingPlus-1.7.10-3.0.2-d.jar) 
	UCHIJAAAA	endercore{1.7.10-0.2.0.39_beta} [EnderCore] (EnderCore-1.7.10-0.2.0.39_beta.jar) 
	UCHIJAAAA	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCHIJAAAA	EnderIO{1.7.10-2.3.0.429_beta} [Ender IO] (EnderIO-1.7.10-2.3.0.429_beta.jar) 
	UCHIJAAAA	ExtraUtilities{1.2.12} [Extra Utilities] (extrautilities-1.2.12.jar) 
	UCHIJAAAA	GalacticraftCore{3.0.12} [Galacticraft Core] (GalacticraftCore-1.7-3.0.12.463.jar) 
	UCHIJAAAA	GalacticraftMars{3.0.12} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.12.463.jar) 
	UCHIJAAAA	GalaxySpace{1.1.2} [GalaxySpace] (GalaxySpace-1.1.2 STABLE.jar) 
	UCHIJAAAA	inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] (InventoryTweaks-1.59-dev-152.jar) 
	UCHIJAAAA	IronChest{6.0.62.742} [Iron Chest] (Iron-Chests-Mod-1.7.10.jar) 
	UCHIJAAAA	journeymap{5.1.4p1} [JourneyMap] (journeymap-1.7.10-5.1.4p1-unlimited.jar) 
	UCHIJAAAA	Mekanism{9.1.0} [Mekanism] (Mekanism-1.7.10-9.1.0.281.jar) 
	UCHIJAAAA	MekanismGenerators{9.1.0} [MekanismGenerators] (MekanismGenerators-1.7.10-9.1.0.281.jar) 
	UCHIJAAAA	MekanismTools{9.1.0} [MekanismTools] (MekanismTools-1.7.10-9.1.0.281.jar) 
	UCHIJAAAA	numina{0.4.0.131} [Numina] (Numina-0.4.0.131.jar) 
	UCHIJAAAA	powersuits{0.11.0.301} [MachineMuse's Modular Powersuits] (ModularPowersuits-0.11.0.301.jar) 
	UCHIJAAAA	OpenMods{0.9.1} [OpenMods] (OpenModsLib-1.7.10-0.9.1.jar) 
	UCHIJAAAA	OpenBlocks{1.5.1} [OpenBlocks] (OpenBlocks-1.7.10-1.5.1.jar) 
	UCHIJAAAA	rfdrills{1.7.3} [RFDrills] (RFDrills-1.7.10-1.7.3.jar) 
	UCHIJAAAA	rftools{4.23} [RFTools] (rftools-4.23.jar) 
	UCHIJAAAA	ThermalDynamics{1.7.10R1.2.0} [Thermal Dynamics] (ThermalDynamics-[1.7.10]1.2.0-171.jar) 
	UCHIJAAAA	WailaHarvestability{1.1.6} [Waila Harvestability] (WailaHarvestability-mc1.7.10-1.1.6.jar) 
	UCHIJAAAA	wailaplugins{MC1.7.10-0.2.0-23} [WAILA Plugins] (WAILAPlugins-MC1.7.10-0.2.0-23.jar) 
	UCHIJAAAA	McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJAAAA	ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	OpenModsLib class transformers: [stencil_patches:FINISHED],[movement_callback:ACTIVATED],[map_gen_fix:FINISHED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
	Class transformer null safety: all safe
	AE2 Version: beta rv3-beta-6 for Forge 10.13.4.1448
	CoFHCore: -[1.7.10]3.1.3-327
	ThermalFoundation: -[1.7.10]1.2.5-115
	ThermalExpansion: -[1.7.10]4.1.4-247
	ThermalDynamics: -[1.7.10]1.2.0-171
	Chisel: Errors like "[FML]: Unable to lookup ..." are NOT the cause of this crash. You can safely ignore these errors. And update forge while you're at it.
	EnderIO: Found the following problem(s) with your installation:
                  * An unknown AE2 API is installed (rv3 from appliedenergistics2-rv3-beta-6.jar).
                    Ender IO was build against API version rv2 and may or may not work with a newer version.
                 This may have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
	Stencil buffer state: Function set: GL30, pool: forge, bits: 8
	AE2 Integration: IC2:OFF, RotaryCraft:OFF, RC:ON, BuildCraftCore:ON, BuildCraftTransport:ON, BuildCraftBuilder:ON, RF:ON, RFItem:ON, MFR:OFF, DSU:ON, FZ:OFF, FMP:ON, RB:OFF, CLApi:OFF, Waila:ON, InvTweaks:ON, NEI:ON, CraftGuide:OFF, Mekanism:ON, ImmibisMicroblocks:OFF, BetterStorage:OFF, OpenComputers:OFF, PneumaticCraft:OFF
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 8; [EntityPlayerMP['KontranRUS'/462, l='Новый мир', x=355.50, y=899.60, z=379.50]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by MeSoLost** [comment]
i'm getting this too when i goto europa to check if the bugs were fixed and now i cant even join my own server unless i loose everything i have or something else drastic. 

edit: ok this is bs =\ even if i use COFH tpx to get to europa i crash. i'm going back to 1.1.1 till you fix this fatal bug -_-

java.lang.NullPointerException: Ticking entity
    at galaxyspace.SolarSystem.planets.overworld.items.ItemArmors.gravityOverrideIfLow(ItemArmors.java:102)
    at micdoodle8.mods.galacticraft.core.util.WorldUtil.getGravityForEntity(WorldUtil.java:124)
    at net.minecraft.entity.EntityLivingBase.func_70612_e(EntityLivingBase.java:1510)
    at net.minecraft.entity.player.EntityPlayer.func_70612_e(EntityPlayer.java:1656)
    at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:1814)
    at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:540)
    at net.minecraft.client.entity.EntityPlayerSP.func_70636_d(EntityPlayerSP.java:287)
    at micdoodle8.mods.galacticraft.core.entities.player.GCEntityClientPlayerMP.func_70636_d(GCEntityClientPlayerMP.java:43)
    at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1611)
    at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:288)
    at net.minecraft.client.entity.EntityClientPlayerMP.func_70071_h_(SourceFile:63)
    at micdoodle8.mods.galacticraft.core.entities.player.GCEntityClientPlayerMP.func_70071_h_(GCEntityClientPlayerMP.java:63)

-- Head --
Stacktrace:
    at galaxyspace.SolarSystem.planets.overworld.items.ItemArmors.gravityOverrideIfLow(ItemArmors.java:102)
    at micdoodle8.mods.galacticraft.core.util.WorldUtil.getGravityForEntity(WorldUtil.java:124)
    at net.minecraft.entity.EntityLivingBase.func_70612_e(EntityLivingBase.java:1510)
    at net.minecraft.entity.player.EntityPlayer.func_70612_e(EntityPlayer.java:1656)
    at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:1814)
    at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:540)
    at net.minecraft.client.entity.EntityPlayerSP.func_70636_d(EntityPlayerSP.java:287)
    at micdoodle8.mods.galacticraft.core.entities.player.GCEntityClientPlayerMP.func_70636_d(GCEntityClientPlayerMP.java:43)
    at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1611)
    at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:288)
    at net.minecraft.client.entity.EntityClientPlayerMP.func_70071_h_(SourceFile:63)
    at micdoodle8.mods.galacticraft.core.entities.player.GCEntityClientPlayerMP.func_70071_h_(GCEntityClientPlayerMP.java:63)

-- Entity being ticked --
Details:
    Entity Type: GalacticraftMars.LandingBalloons (micdoodle8.mods.galacticraft.planets.mars.entities.EntityLandingBalloons)
    Entity ID: 291
    Entity Name: Landing Balloons
    Entity's Exact location: 116.50, 900.00, 895.50
    Entity's Block location: World: (116,900,895), Chunk: (at 4,56,15 in 7,55; contains blocks 112,0,880 to 127,255,895), Region: (0,1; contains chunks 0,32 to 31,63, blocks 0,0,512 to 511,255,1023)
    Entity's Momentum: 0.00, 0.00, 0.00

**Comment by BlesseNtumble** [comment]
We know about the error. Already fixed in 1.1.3
