### ISSUE TITLE
[1.1.8] java.lang.NullPointerException: Exception generating new chunk

### ISSUE THREAD

**Issue by 4erk** [BlesseNtumble/GalaxySpace#191]
Когда запускаешь ракету лететь на другую планету во время отсчета сервер крашится. После перезапуска сервера же можно выбирать планету и лететь

---- Minecraft Crash Report ----
// I'm sorry, Dave.

Time: 10/15/17 5:36 PM
Description: Exception generating new chunk

java.lang.NullPointerException: Exception generating new chunk
	at galaxyspace.SolarSystem.core.world.gen.ChunkProviderSpaceCraters.replaceBlocksForBiome(Unknown Source)
	at galaxyspace.SolarSystem.core.world.gen.ChunkProviderSpaceCraters.func_73154_d(Unknown Source)
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:259)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:217)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:185)
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:323)
	at net.minecraft.world.World.func_72964_e(World.java:799)
	at micdoodle8.mods.galacticraft.api.prefab.entity.EntityTieredRocket.func_70071_h_(EntityTieredRocket.java:225)
	at galaxyspace.SolarSystem.planets.pluto.entities.EntityTier8Rocket.func_70071_h_(Unknown Source)
	at net.minecraft.world.World.func_72866_a(World.java:2740)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:877)
	at net.minecraft.world.World.func_72870_g(World.java:2678)
	at net.minecraft.world.World.func_72939_s(World.java:2480)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:673)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:986)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693)
	at java.lang.Thread.run(Thread.java:748)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at galaxyspace.SolarSystem.core.world.gen.ChunkProviderSpaceCraters.replaceBlocksForBiome(Unknown Source)
	at galaxyspace.SolarSystem.core.world.gen.ChunkProviderSpaceCraters.func_73154_d(Unknown Source)

-- Chunk to be generated --
Details:
	Location: -14,7
	Position hash: -57982058489
	Generator: RandomLevelSource
Stacktrace:
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:259)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:217)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:185)
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:323)
	at net.minecraft.world.World.func_72964_e(World.java:799)
	at micdoodle8.mods.galacticraft.api.prefab.entity.EntityTieredRocket.func_70071_h_(EntityTieredRocket.java:225)
	at galaxyspace.SolarSystem.planets.pluto.entities.EntityTier8Rocket.func_70071_h_(Unknown Source)
	at net.minecraft.world.World.func_72866_a(World.java:2740)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:877)
	at net.minecraft.world.World.func_72870_g(World.java:2678)

-- Entity being ticked --
Details:
	Entity Type: GalacticraftCore.SpaceshipT8 (galaxyspace.SolarSystem.planets.pluto.entities.EntityTier8Rocket)
	Entity ID: 5364
	Entity Name: entity.GalacticraftCore.SpaceshipT8.name
	Entity's Exact location: -128.50, 1114.40, 163.50
	Entity's Block location: World: (-129,1114,163), Chunk: (at 15,69,3 in -9,10; contains blocks -144,0,160 to -129,255,175), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: -0.00, 2.50, -0.00
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:2480)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:673)

-- Affected level --
Details:
	Level name: DIM-1026
	All players: 1 total; [GCEntityPlayerMP['4erk'/205, l='DIM-1026', x=-128.50, y=1112.15, z=163.50](4erk at -128.5,1112.1500001234003,163.5)]
	Chunk stats: ServerChunkCache: 289 Drop: 0
	Level seed: 135
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (0,64,0), Chunk: (at 0,4,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 27188 game time, 27188 day time
	Level dimension: -1026
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:986)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693)
	at java.lang.Thread.run(Thread.java:748)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Thermos Version: cyberdynecc:Thermos:1.7.10-1614.57
	Plugins: 
	Disabled Plugins: 
	Operating System: Linux (amd64) version 2.6.32-openvz-amd64
	Java Version: 1.8.0_144, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 893814816 bytes (852 MB) / 1900019712 bytes (1812 MB) up to 2863661056 bytes (2731 MB)
	JVM Flags: 1 total; -Xmx3072m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 39, allocated: 3, tallocated: 42
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 39 mods loaded, 39 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (server.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (server.jar) 
	UCHIJAAAA	kimagine{0.2} [KImagine] (minecraft.jar) 
	UCHIJAAAA	appliedenergistics2-core{rv3-beta-6} [Applied Energistics 2 Core] (minecraft.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
	UCHIJAAAA	appliedenergistics2{rv3-beta-6} [Applied Energistics 2] (appliedenergistics2-rv3-beta-6.jar) 
	UCHIJAAAA	endercore{1.7.10-0.2.0.39_beta} [EnderCore] (EnderCore-1.7.10-0.2.0.39_beta.jar) 
	UCHIJAAAA	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCHIJAAAA	EnderIO{1.7.10-2.3.0.432_beta.0_master_b646a59} [Ender IO] (EnderIO-1.7.10-2.3.0.432_beta.jar) 
	UCHIJAAAA	extracells{2.3.14} [Extra Cells 2] (ExtraCells-1.7.10-2.3.14b199.jar) 
	UCHIJAAAA	ExtraUtilities{1.2.12} [Extra Utilities] (extrautilities-1.2.13.jar) 
	UCHIJAAAA	IC2{2.2.827-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.827-experimental.jar) 
	UCHIJAAAA	Forestry{4.2.16.64} [Forestry for Minecraft] (forestry_1.7.10-4.2.16.64.jar) 
	UCHIJAAAA	GalacticraftCore{3.0.12} [Galacticraft Core] (GalacticraftCore-1.7-3.0.12.502.jar) 
	UCHIJAAAA	GalacticraftMars{3.0.12} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.12.502.jar) 
	UCHIJAAAA	gregtech{MC1710} [GregTech] (gregtech-5.09.31.jar) 
	UCHIJAAAA	galacticgreg{0.9.6} [Galactic Greg] (GalacticGreg-1.7.10-0.9.6.jar) 
	UCHIJAAAA	GalaxySpace{1.1.8} [GalaxySpace] (GalaxySpace-1.1.8 STABLE.jar) 
	UCHIJAAAA	GraviSuite{2.0.68u} [Graviation Suite] (GraviSuite-1.7.10-2.0.68u.jar) 
	UCHIJAAAA	miscutils{1.6.07-release} [GT++] (GT-PlusPlus-1.6.07-release.jar) 
	UCHIJAAAA	GT++DarkWorld{1.6.07-release} [GT++ Dark World] (GT-PlusPlus-1.6.07-release.jar) 
	UCHIJAAAA	GTTweaker{1.0} [GTTweaker] (GTTweaker-1.7.10-1.6.3.jar) 
	UCHIJAAAA	inventorytweaks{1.59-dev-156-af3bc68} [Inventory Tweaks] (InventoryTweaks-1.59-dev-156.jar) 
	UCHIJAAAA	IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) 
	UCHIJAAAA	MineTweaker3{3.0.10} [MineTweaker 3] (MineTweaker3-1.7.10-3.0.10B.jar) 
	UCHIJAAAA	modtweaker2{0.9.6} [Mod Tweaker 2] (ModTweaker2-0.9.6.jar) 
	UCHIJAAAA	NEIAddons{1.12.15.41} [NEI Addons] (neiaddons-1.12.15.41-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|Developer{1.12.15.41} [NEI Addons: Developer Tools] (neiaddons-1.12.15.41-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|AppEng{1.12.15.41} [NEI Addons: Applied Energistics 2] (neiaddons-1.12.15.41-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|Botany{1.12.15.41} [NEI Addons: Botany] (neiaddons-1.12.15.41-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|Forestry{1.12.15.41} [NEI Addons: Forestry] (neiaddons-1.12.15.41-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|CraftingTables{1.12.15.41} [NEI Addons: Crafting Tables] (neiaddons-1.12.15.41-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|ExNihilo{1.12.15.41} [NEI Addons: Ex Nihilo] (neiaddons-1.12.15.41-mc1.7.10.jar) 
	UCHIJAAAA	WailaHarvestability{1.1.6} [Waila Harvestability] (WailaHarvestability-mc1.7.10-1.1.6.jar) 
	UCHIJAAAA	wailaplugins{MC1.7.10-0.2.0-25} [WAILA Plugins] (WAILAPlugins-MC1.7.10-0.2.0-25.jar) 
	UCHIJAAAA	wawla{1.3.1} [What Are We Looking At] (Wawla-1.0.5.120.jar) 
	AE2 Version: beta rv3-beta-6 for Forge 10.13.4.1448
	EnderIO: Found the following problem(s) with your installation:
                  * An unknown AE2 API is installed (rv3 from appliedenergistics2-rv3-beta-6.jar).
                    Ender IO was build against API version rv2 and may or may not work with a newer version.
                 An unsupported base software is installed: 'thermos, cauldron, craftbukkit, mcpc, kcauldron'. This is NOT supported.
                 This may have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
	Forestry : Warning: You have mods that change the behavior of Minecraft, ForgeModLoader, and/or Minecraft Forge to your client: 
Bukkit, Cauldron, or other Bukkit replacement
These may have caused this error, and may not be supported. Try reproducing the crash WITHOUT these mods, and report it then.
	AE2 Integration: IC2:ON, RotaryCraft:OFF, RC:OFF, BuildCraftCore:OFF, BuildCraftTransport:OFF, BuildCraftBuilder:OFF, RF:ON, RFItem:ON, MFR:OFF, DSU:ON, FZ:OFF, FMP:OFF, RB:OFF, CLApi:OFF, Waila:ON, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF, OpenComputers:OFF, PneumaticCraft:OFF
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 20; [GCEntityPlayerMP['4erk'/205, l='DIM-1026', x=-128.50, y=1112.15, z=163.50](4erk at -128.5,1112.1500001234003,163.5)]
	Is Modded: Definitely; Server brand changed to 'thermos,cauldron,craftbukkit,mcpc,kcauldron,fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by 4erk** [comment]
Для нормальной работы пока потребовалось выключить плутон. Кстати, при полете на него там прогружалась карта сгенеренная на земле, правда с небом плутона и ег гравитацией.
