### ISSUE TITLE
Crash when opening GalacticMap

### ISSUE THREAD

**Issue by Maxx138** [BlesseNtumble/GalaxySpace#194]
Hello,

I've been having this issue I have a server with some friends wich has 4Space, Galacticraft 3, More planets and GalaxySpace now I have been getting this issue on the server with these mods and singleplayer I dont know if its a mod colition.

Crash report:
---- Minecraft Crash Report ----
// On the bright side, I bought you a teddy bear!

Time: 15-11-17 16:33
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
	at micdoodle8.mods.galacticraft.core.client.gui.screen.GuiCelestialSelection.getCelestialBodyPosition(GuiCelestialSelection.java:1172)
	at micdoodle8.mods.galacticraft.core.client.gui.screen.GuiCelestialSelection.getCelestialBodyPosition(GuiCelestialSelection.java:1185)
	at galaxyspace.SolarSystem.core.coremod.gui.screen.GSGuiCelestialSelection.drawCelestialBodies(Unknown Source)
	at galaxyspace.SolarSystem.core.coremod.gui.screen.GSGuiCelestialSelection.func_73863_a(Unknown Source)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1455)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at micdoodle8.mods.galacticraft.core.client.gui.screen.GuiCelestialSelection.getCelestialBodyPosition(GuiCelestialSelection.java:1172)
	at micdoodle8.mods.galacticraft.core.client.gui.screen.GuiCelestialSelection.getCelestialBodyPosition(GuiCelestialSelection.java:1185)
	at galaxyspace.SolarSystem.core.coremod.gui.screen.GSGuiCelestialSelection.drawCelestialBodies(Unknown Source)
	at galaxyspace.SolarSystem.core.coremod.gui.screen.GSGuiCelestialSelection.func_73863_a(Unknown Source)

-- Screen render details --
Details:
	Screen name: galaxyspace.SolarSystem.core.coremod.gui.screen.GSGuiCelestialSelection
	Mouse location: Scaled: (480, 254). Absolute: (960, 508)
	Screen size: Scaled: (960, 509). Absolute: (1920, 1017). Scale factor of 2

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [GCEntityClientPlayerMP['___Maxx___'/462, l='MpServer', x=349,50, y=73,62, z=-379,50]]
	Chunk stats: MultiplayerChunkCache: 289, 298
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (345,64,-372), Chunk: (at 9,4,12 in 21,-24; contains blocks 336,0,-384 to 351,255,-369), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 280 game time, 280 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 111 total; [EntitySkeleton['Skeleton'/1040, l='MpServer', x=381,50, y=48,00, z=-366,50], EntityCreeper['Creeper'/1096, l='MpServer', x=326,56, y=38,00, z=-321,50], EntityCreeper['Creeper'/1097, l='MpServer', x=324,50, y=37,00, z=-320,00], EntityCreeper['Creeper'/1098, l='MpServer', x=325,59, y=37,00, z=-321,63], EntitySpider['Spider'/1102, l='MpServer', x=313,72, y=22,00, z=-304,72], EntitySkeleton['Skeleton'/1104, l='MpServer', x=310,50, y=59,00, z=-318,50], MoCEntityRat['Rat'/1107, l='MpServer', x=350,50, y=24,00, z=-283,50], EntitySkeleton['Skeleton'/1111, l='MpServer', x=315,55, y=53,00, z=-327,74], GCEntityClientPlayerMP['___Maxx___'/462, l='MpServer', x=349,50, y=73,62, z=-379,50], EntitySkeleton['Skeleton'/606, l='MpServer', x=358,50, y=16,00, z=-304,50], EntityCreeper['Creeper'/614, l='MpServer', x=368,50, y=43,00, z=-329,50], MoCEntityDragonfly['DragonFly'/618, l='MpServer', x=352,41, y=90,00, z=-468,47], MoCEntityBee['Bee'/619, l='MpServer', x=314,19, y=66,00, z=-279,47], MoCEntityAnt['Ant'/620, l='MpServer', x=326,50, y=70,00, z=-306,50], EntityBat['Bat'/623, l='MpServer', x=322,49, y=35,71, z=-335,84], MoCEntityFly['Fly'/626, l='MpServer', x=405,50, y=80,00, z=-410,50], EntityZombie['Zombie'/1158, l='MpServer', x=420,50, y=27,00, z=-417,50], EntityCreeper['Creeper'/1161, l='MpServer', x=270,50, y=14,00, z=-314,50], MoCEntityWerewolf['Werewolf'/1162, l='MpServer', x=309,19, y=55,00, z=-321,97], EntitySkeleton['Skeleton'/1164, l='MpServer', x=324,50, y=26,00, z=-318,50], EntityEarthCreeper['Earth Creeper'/1165, l='MpServer', x=321,50, y=55,00, z=-322,50], MoCEntityScorpion['Scorpion'/1182, l='MpServer', x=294,41, y=24,00, z=-404,26], EntityTrail['unknown'/2735, l='MpServer', x=349,50, y=73,62, z=-379,50], EntityCreeper['Creeper'/1204, l='MpServer', x=332,50, y=19,00, z=-316,50], EntitySpider['Spider'/1206, l='MpServer', x=300,06, y=30,00, z=-337,00], EntityCreeper['Creeper'/1207, l='MpServer', x=413,50, y=27,00, z=-411,50], EntityCreeper['Creeper'/1208, l='MpServer', x=410,50, y=27,00, z=-408,50], EntityCreeper['Creeper'/1231, l='MpServer', x=317,50, y=22,00, z=-307,50], EntityZombie['Zombie'/1279, l='MpServer', x=317,50, y=33,00, z=-345,50], EntityCreeper['Creeper'/1280, l='MpServer', x=291,50, y=50,00, z=-380,50], EntityCreeper['Creeper'/1281, l='MpServer', x=374,50, y=21,00, z=-332,50], EntitySkeleton['Skeleton'/1282, l='MpServer', x=370,97, y=21,00, z=-330,56], EntitySkeleton['Skeleton'/1284, l='MpServer', x=388,50, y=44,00, z=-360,50], EntitySkeleton['Skeleton'/1288, l='MpServer', x=348,50, y=36,00, z=-316,50], EntityZombie['Zombie'/1306, l='MpServer', x=317,50, y=33,00, z=-344,50], EntityZombie['Zombie'/1307, l='MpServer', x=315,50, y=33,00, z=-345,50], EntitySpider['Spider'/1308, l='MpServer', x=403,72, y=71,08, z=-426,84], EntityZombie['Zombie'/1309, l='MpServer', x=345,50, y=46,00, z=-420,50], EntityZombie['Zombie'/1311, l='MpServer', x=304,50, y=32,00, z=-307,50], EntityZombie['Zombie'/1312, l='MpServer', x=304,50, y=32,00, z=-305,50], MoCEntityDuck['Duck'/291, l='MpServer', x=241,50, y=71,00, z=-290,50], EntitySkeleton['Skeleton'/1315, l='MpServer', x=407,50, y=72,00, z=-426,50], MoCEntityDuck['Duck'/292, l='MpServer', x=244,50, y=71,00, z=-290,50], MoCEntityDuck['Duck'/293, l='MpServer', x=239,50, y=76,00, z=-273,50], MoCEntityDuck['Duck'/316, l='MpServer', x=296,09, y=73,00, z=-381,06], MoCEntityDuck['Duck'/317, l='MpServer', x=297,50, y=73,00, z=-380,50], MoCEntityBoar['Boar'/318, l='MpServer', x=301,50, y=72,00, z=-313,50], MoCEntityBoar['Boar'/319, l='MpServer', x=300,50, y=76,00, z=-317,50], MoCEntityMole['Mole'/320, l='MpServer', x=296,69, y=63,00, z=-294,47], EntityWolf['Wolf'/324, l='MpServer', x=338,50, y=69,00, z=-432,50], EntityWolf['Wolf'/325, l='MpServer', x=342,28, y=68,00, z=-426,53], EntityWolf['Wolf'/326, l='MpServer', x=336,50, y=70,00, z=-431,50], EntityWolf['Wolf'/327, l='MpServer', x=335,50, y=70,00, z=-433,50], MoCEntityDuck['Duck'/328, l='MpServer', x=343,47, y=81,00, z=-354,75], EntitySkeleton['Skeleton'/1366, l='MpServer', x=403,72, y=71,25, z=-426,84], EntitySheep['Sheep'/345, l='MpServer', x=364,80, y=78,00, z=-310,32], EntitySheep['Sheep'/346, l='MpServer', x=356,50, y=72,00, z=-323,50], EntitySheep['Sheep'/347, l='MpServer', x=353,50, y=71,00, z=-324,50], EntitySheep['Sheep'/348, l='MpServer', x=354,50, y=75,00, z=-324,50], EntityPig['Pig'/349, l='MpServer', x=361,47, y=72,00, z=-318,34], EntityPig['Pig'/350, l='MpServer', x=357,63, y=71,00, z=-315,19], EntityPig['Pig'/351, l='MpServer', x=355,50, y=71,00, z=-317,50], EntityPig['Pig'/352, l='MpServer', x=350,19, y=71,00, z=-306,66], EntityItem['item.tile.mushroom'/357, l='MpServer', x=377,88, y=38,13, z=-369,06], MoCEntitySnake['Snake'/358, l='MpServer', x=362,72, y=71,00, z=-271,19], EntitySheep['Sheep'/367, l='MpServer', x=406,31, y=80,00, z=-414,78], EntitySheep['Sheep'/368, l='MpServer', x=404,72, y=80,00, z=-415,94], EntitySheep['Sheep'/369, l='MpServer', x=406,50, y=80,00, z=-418,59], EntitySheep['Sheep'/370, l='MpServer', x=406,28, y=80,00, z=-417,41], EntityChicken['Chicken'/371, l='MpServer', x=403,50, y=71,00, z=-364,50], EntityChicken['Chicken'/372, l='MpServer', x=401,50, y=71,00, z=-365,50], EntityChicken['Chicken'/373, l='MpServer', x=397,50, y=72,00, z=-369,50], EntityChicken['Chicken'/374, l='MpServer', x=397,50, y=71,00, z=-367,50], MoCEntityGoat['Goat'/375, l='MpServer', x=397,50, y=78,00, z=-258,50], MoCEntityGoat['Goat'/376, l='MpServer', x=398,84, y=69,00, z=-262,50], MoCEntityGoat['Goat'/379, l='MpServer', x=411,13, y=84,00, z=-411,59], MoCEntityGoat['Goat'/380, l='MpServer', x=404,28, y=79,96, z=-421,50], MoCEntityGoat['Goat'/381, l='MpServer', x=413,28, y=85,00, z=-412,09], MoCEntityDuck['Duck'/382, l='MpServer', x=421,53, y=69,00, z=-275,53], MoCEntityDuck['Duck'/383, l='MpServer', x=421,50, y=69,00, z=-279,50], MoCEntityGoat['Goat'/388, l='MpServer', x=430,91, y=74,00, z=-350,25], EntitySpider['Spider'/901, l='MpServer', x=383,28, y=57,00, z=-320,03], MoCEntityGoat['Goat'/389, l='MpServer', x=427,16, y=73,00, z=-346,13], EntityCreeper['Creeper'/902, l='MpServer', x=364,50, y=43,00, z=-331,50], MoCEntityHorse['WildHorse'/390, l='MpServer', x=430,50, y=70,00, z=-331,50], EntityCreeper['Creeper'/903, l='MpServer', x=322,50, y=35,00, z=-329,50], MoCEntityHorse['WildHorse'/391, l='MpServer', x=429,38, y=71,00, z=-334,28], MoCEntityHorse['WildHorse'/392, l='MpServer', x=435,50, y=75,00, z=-331,50], EntityZombie['Zombie'/905, l='MpServer', x=371,50, y=46,00, z=-340,50], MoCEntityHorse['WildHorse'/393, l='MpServer', x=433,16, y=75,00, z=-331,22], MoCEntityGoat['Goat'/395, l='MpServer', x=453,38, y=68,00, z=-294,47], EntityZombie['Zombie'/908, l='MpServer', x=397,50, y=46,00, z=-355,50], MoCEntityGoat['Goat'/396, l='MpServer', x=452,97, y=68,00, z=-296,84], MoCEntityAnt['Ant'/909, l='MpServer', x=323,69, y=70,00, z=-300,34], MoCEntityGoat['Goat'/397, l='MpServer', x=449,19, y=68,00, z=-296,41], MoCEntityAnt['Ant'/910, l='MpServer', x=323,41, y=70,00, z=-300,56], MoCEntityAnt['Ant'/911, l='MpServer', x=322,50, y=70,00, z=-297,50], MoCEntitySnail['Snail'/913, l='MpServer', x=332,47, y=80,00, z=-483,50], MoCEntityButterfly['ButterFly'/914, l='MpServer', x=316,50, y=67,00, z=-280,50], EntitySkeleton['Skeleton'/923, l='MpServer', x=289,50, y=65,00, z=-325,50], EntityPsyhicCreeper['Psychic Creeper'/924, l='MpServer', x=356,00, y=34,00, z=-397,41], MoCEntityButterfly['ButterFly'/926, l='MpServer', x=228,50, y=73,00, z=-377,50], MoCEntityButterfly['ButterFly'/928, l='MpServer', x=227,50, y=69,00, z=-310,50], MoCEntityButterfly['ButterFly'/929, l='MpServer', x=225,31, y=69,00, z=-311,44], MoCEntityButterfly['ButterFly'/930, l='MpServer', x=225,63, y=69,00, z=-309,63], MoCEntitySnail['Snail'/931, l='MpServer', x=225,50, y=69,00, z=-307,50], MoCEntityCricket['Cricket'/932, l='MpServer', x=409,50, y=80,00, z=-406,50], EntitySkeleton['Skeleton'/934, l='MpServer', x=292,50, y=65,00, z=-324,50], MoCEntityRat['Rat'/940, l='MpServer', x=352,75, y=42,00, z=-415,50], EntityItem['item.tile.torch'/1503, l='MpServer', x=289,69, y=32,13, z=-412,81], EntityCreeper['Creeper'/1013, l='MpServer', x=311,50, y=22,00, z=-335,50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:425)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 391103600 bytes (372 MB) / 1073741824 bytes (1024 MB) up to 1073741824 bytes (1024 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 1, tcache: 1, allocated: 12, tallocated: 94
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 Optifine OptiFine_1.7.10_HD_U_D8 44 mods loaded, 44 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal (1).jar) 
	UCHIJAAAA	TooManyItems{1.7.10} [TooManyItems] (minecraft.jar) 
	UCHIJAAAA	GalacticraftCore{3.0.12} [Galacticraft Core] (GalacticraftCore-1.7-3.0.12.502.jar) 
	UCHIJAAAA	SpaceCore{4.1.9} [4Space Core] (4Space-4.1.9 (1).jar) 
	UCHIJAAAA	ExoCore{0.1.2} [4Space Exoplanets Core] (4Space-4.1.9 (1).jar) 
	UCHIJAAAA	ExoElipse{0.1.2} [4Space Exoplanets Elipse] (4Space-4.1.9 (1).jar) 
	UCHIJAAAA	SpaceCallisto{4.1.9} [4Space Callisto] (4Space-4.1.9 (1).jar) 
	UCHIJAAAA	SpaceEuropa{4.1.9} [4Space Europa] (4Space-4.1.9 (1).jar) 
	UCHIJAAAA	SpaceVenus{4.1.9} [4Space Venus] (4Space-4.1.9 (1).jar) 
	UCHIJAAAA	SpaceIo{4.1.9} [4Space Io] (4Space-4.1.9 (1).jar) 
	UCHIJAAAA	SpaceMercury{4.1.9} [4Space Mercury] (4Space-4.1.9 (1).jar) 
	UCHIJAAAA	SpacePluto{4.1.9} [4Space Pluto] (4Space-4.1.9 (1).jar) 
	UCHIJAAAA	lucky{5.1.0} [Lucky Block] ([1-7-10]_Lucky_Block_v5-1-0.jar) 
	UCHIJAAAA	securitycraft{v1.8.2.3-hotfix} [SecurityCraft] ([1.7.10] SecurityCraft v1.8.2.3-hotfix.jar) 
	UCHIJAAAA	BBG{1.0.0} [BetterBedrockGen] (BetterBedrockGen-Mod-1.7.10.jar) 
	UCHIJAAAA	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.1640-universal.jar) 
	UCHIJAAAA	cannibalism{1.3.0} [Cannibalism] (Cannibalism-1.3.0-1.7.10.jar) 
	UCHIJAAAA	cfm{3.4.8} [§9MrCrayfish's Furniture Mod] (cfm-3.4.8-mc1.7.10.jar) 
	UCHIJAAAA	chisel{2.9.5.11} [Chisel] (Chisel-Mod-1.7.10.jar) 
	UCHIJAAAA	lootablebodies{1.3.7} [DrCyano's Lootable Bodies] (CyanosLootableBodies-1.7.10-backport_1.3.7.jar) 
	UCHIJAAAA	DamageIndicatorsMod{3.2.0} [Damage Indicators] (Damage-Indicators-Mod-1.7.10.jar) 
	UCHIJAAAA	MoCreatures{6.3.1} [DrZhark's Mo'Creatures Mod] (DrZharks MoCreatures Mod v6.3.1.zip) 
	UCHIJAAAA	elementalcreepers{4.3.0} [Elemental Creepers] (Elemental Creepers-universal_1.7.10-4.3.0.jar) 
	UCHIJAAAA	evilcraft{0.9.12} [EvilCraft] (EvilCraft-Mod-1.7.10.jar) 
	UCHIJAAAA	explosives_pp{1.7b} [§6Explosives§4++] (ExplosivesPP-1.7.10-1.7b.jar) 
	UCHIJAAAA	fastleafdecay{1.3} [Fast Leaf Decay] (FastLeafDecay-Mod-1.7.10.jar) 
	UCHIJAAAA	ftfloocraft{1.7.10-1.7} [Floocraft] (Floocraft-Mod-1.7.10.jar) 
	UCHIJAAAA	GalacticraftMars{3.0.12} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.12.502.jar) 
	UCHIJAAAA	GalaxySpace{1.1.9} [GalaxySpace] (GalaxySpace-1.1.9 STABLE.jar) 
	UCHIJAAAA	grapplemod{1.7.10-v10} [Grappling hook mod] (Grappling-Hook-Mod-1.7.10.jar) 
	UCHIJAAAA	iChunUtil{4.2.2} [iChunUtil] (iChunUtil-4.2.2.jar) 
	UCHIJAAAA	malisiscore{1.7.10-0.14.3} [MalisisCore] (malisiscore-1.7.10-0.14.3.jar) 
	UCHIJAAAA	malisisdoors{1.7.10-1.13.0} [Malisis' Doors] (malisisdoors-1.7.10-1.13.0.jar) 
	UCHIJAAAA	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) 
	UCHIJAAAA	MorePlanet{1.4.3} [More Planets] (More-Planets-1.7.10-1.4.3-GC502.jar) 
	UCHIJAAAA	PortalGun{4.0.0-beta-6} [PortalGun] (Portal-Gun-Mod-1.7.10 (1).jar) 
	UCHIJAAAA	secretroomsmod{4.7.1} [The SecretRoomsMod] (secretroomsmod-1.7.10-4.7.1.412.jar) 
	UCHIJAAAA	TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct] (TConstruct-1.7.10-1.8.8.jar) 
	UCHIJAAAA	SpecialArmor{1.7.10} [TeeLuk's SpecialArmor] (TLSpecialArmor-1.7.10.jar) 
	Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: optifine
	TConstruct Environment: Environment healthy.
	Chisel: Errors like "[FML]: Unable to lookup ..." are NOT the cause of this crash. You can safely ignore these errors. And update forge while you're at it.
	Launched Version: 1.7.10-Forge10.13.4.1614-1.7.10
	LWJGL: 2.9.1
	OpenGL: Intel(R) HD Graphics 4600 GL version 4.2.0 - Build 10.18.10.3496, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)
	OptiFine Version: OptiFine_1.7.10_HD_U_D8
	Render Distance Chunks: 8
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.2.0 - Build 10.18.10.3496
	OpenGlRenderer: Intel(R) HD Graphics 4600
	OpenGlVendor: Intel
	CpuCount: 4
[crash-2017-11-15_16.33.21-client.txt](https://github.com/BlesseNtumble/GalaxySpace/files/1475318/crash-2017-11-15_16.33.21-client.txt)

**Comment by Maxx138** [comment]
My friends have these problems to

**Comment by Maxx138** [comment]
I also have when loading the server, it shows that I have missing item ids

**Comment by Maxx138** [comment]
Hey, I've fixxed this by upgrading from vers. 1.1.4 to 1.1.5 probably gonna try 1.1.6 to
