### ISSUE TITLE
Bug no Crash [Tile Entity Dungeon Spawner Venus is missing a mapping!]

### ISSUE THREAD

**Issue by Dream-Master** [BlesseNtumble/GalaxySpace#2]
Get this in my forge log:

using Version 1.6

````````````````````````````````````````````````````````````

[19:19:29] [Server thread/ERROR] [FML/]: A TileEntity type blessentumble.planets.venus.tile.TileEntityDungeonSpawnerVenus has throw an exception trying to write state. It will not persist. Report this to the mod author
java.lang.RuntimeException: class blessentumble.planets.venus.tile.TileEntityDungeonSpawnerVenus is missing a mapping! This is a bug!
	at net.minecraft.tileentity.TileEntity.func_145841_b(TileEntity.java:80) ~[aor.class:?]
	at micdoodle8.mods.galacticraft.core.tile.TileEntityDungeonSpawner.func_145841_b(TileEntityDungeonSpawner.java:179) ~[TileEntityDungeonSpawner.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunkLoader.java:370) [aqk.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:197) [aqk.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:256) [ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73151_a(ChunkProviderServer.java:302) [ms.class:?]
	at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:809) [mt.class:?]
	at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:318) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:569) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
[19:19:29] [Server thread/ERROR] [FML/]: A TileEntity type blessentumble.planets.venus.tile.TileEntityDungeonSpawnerVenus has throw an exception trying to write state. It will not persist. Report this to the mod author
java.lang.RuntimeException: class blessentumble.planets.venus.tile.TileEntityDungeonSpawnerVenus is missing a mapping! This is a bug!
	at net.minecraft.tileentity.TileEntity.func_145841_b(TileEntity.java:80) ~[aor.class:?]
	at micdoodle8.mods.galacticraft.core.tile.TileEntityDungeonSpawner.func_145841_b(TileEntityDungeonSpawner.java:179) ~[TileEntityDungeonSpawner.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunkLoader.java:370) [aqk.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:197) [aqk.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:256) [ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73156_b(ChunkProviderServer.java:343) [ms.class:?]
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:165) [mt.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:625) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
``````````````````````````````````````

**Comment by SteveKunG** [comment]
Hi. I'm creator of More Planets Mod. I think @BlesseNtumble He forgot to register Tile Entity.
