### ISSUE TITLE
Galaxy X Space & Sulphur Ore

### ISSUE THREAD

**Issue by sfxworks** [BlesseNtumble/GalaxySpace#215]
Per a user of our server:

BUG: When looking at the recipes for Galaxy space Sulphur ore, the game will crash with a render error as shown below

```
Rendering item
java.lang.ArrayIndexOutOfBoundsException: 5
    at galaxyspace.SolarSystem.moons.proteus.blocks.ProteusBlocks.func_149691_a(Unknown Source)
    at net.minecraft.client.renderer.RenderBlocks.func_147787_a(RenderBlocks.java:8232)
    at net.minecraft.client.renderer.RenderBlocks.func_147800_a(RenderBlocks.java:8161)
    at net.minecraft.client.renderer.entity.RenderItem.renderItemIntoGUI(RenderItem.java:446)
    at net.minecraft.client.renderer.entity.RenderItem.func_82406_b(RenderItem.java:565)
    at codechicken.nei.guihook.GuiContainerManager.drawSlotItem(GuiContainerManager.java:489)
    at net.minecraft.client.gui.inventory.GuiContainer.func_146977_a(GuiContainer.java:270)
    at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:99)
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

Using GalaxySpace-1.1.9+STABLE.jar

**Comment by BlesseNtumble** [comment]
Update GS.
Actual version - 1.2.1
