### ISSUE TITLE
solar wind generator crash

### ISSUE THREAD

**Issue by lexx1191** [BlesseNtumble/GalaxySpace#216]
when installing solar wind generator crash tick GalaxySpace-1.1.3a 
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 4/3/18 10:43 PM
Description: Ticking block entity

java.lang.NoSuchFieldError: ticks
	at galaxyspace.SolarSystem.planets.overworld.tile.TileEntitySolarWind.func_145845_h(TileEntitySolarWind.java:102)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:

[crash-2018-04-03_22.43.15-server.txt](https://github.com/BlesseNtumble/GalaxySpace/files/1872912/crash-2018-04-03_22.43.15-server.txt)

the issue decided to upgrade to the latest version

**Comment by BlesseNtumble** [comment]
update GS
