### ISSUE TITLE
A minecraft crash report.

### ISSUE THREAD

**Issue by Sandendaty** [BlesseNtumble/GalaxySpace#227]
GalaxySpace version 1.2.3
GalactiCraft version 3.0.12.503
I went to the moon dungeon and got the schematic box in survival mode,then open it and got 5 schematics.I put one of them into the NASA workbench to unlock the recipe of rocket part,then reopen the NASA workbench's GUI,clicked "Next page",the game crash.I restart minecraft to do it over and over again,and I realize that minecraft sometimes crash,sometimes not crash.This is the crash report.

`
Description: Updating screen events
java.lang.BootstrapMethodError: call site initialization exception
	at java.lang.invoke.CallSite.makeSite(Unknown Source)
	at java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(Unknown Source)
	at java.lang.invoke.MethodHandleNatives.linkCallSite(Unknown Source)
	at galaxyspace.galaxies.milkyway.systems.SolarSystem.planets.overworld.inventory.schematics.ContainerSchematicBooster.func_75130_a(Unknown Source)
	at galaxyspace.galaxies.milkyway.systems.SolarSystem.planets.overworld.inventory.schematics.ContainerSchematicBooster.<init>(Unknown Source)
	at galaxyspace.galaxies.milkyway.systems.SolarSystem.planets.overworld.gui.schematics.GuiSchematicBooster.<init>(Unknown Source)
	at galaxyspace.galaxies.milkyway.systems.SolarSystem.planets.overworld.schematic.SchematicBooster.getResultScreen(Unknown Source)
	at micdoodle8.mods.galacticraft.core.client.gui.GuiHandler.getClientGuiElement(GuiHandler.java:268)
	at micdoodle8.mods.galacticraft.core.client.gui.GuiHandler.getClientGuiElement(GuiHandler.java:147)
	at cpw.mods.fml.common.network.NetworkRegistry.getLocalGuiContainer(NetworkRegistry.java:265)
	at cpw.mods.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:93)
	at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2209)
	at micdoodle8.mods.galacticraft.core.event.EventHandlerGC.schematicFlipEvent(EventHandlerGC.java:575)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_241_EventHandlerGC_schematicFlipEvent_FlipPage.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at micdoodle8.mods.galacticraft.api.recipe.SchematicRegistry.flipToNextPage(SchematicRegistry.java:119)
	at micdoodle8.mods.galacticraft.core.client.gui.container.GuiSchematicTier1Rocket.func_146284_a(GuiSchematicTier1Rocket.java:47)
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:225)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java:326)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:296)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146274_d(GuiContainer.java)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1640)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassCastException: bootstrap method failed to produce a CallSite
	... 33 more
`

**Comment by Sandendaty** [comment]
I'm sorry, I forgot to add the description that day. Now this issue has been corrected.

**Comment by BlesseNtumble** [comment]
only crashes because of this schematic ContainerSchematicBooster?

**Comment by Sandendaty** [comment]
Not only,maybe all of the rocket parts.

**Comment by BlesseNtumble** [comment]
Do you have other addons?

**Comment by Sandendaty** [comment]
Yes.OK,now I delete all the addons except Galacticraft and GalaxySpace then restart minecraft,but the problem still can't solve.

**Comment by Sandendaty** [comment]
@BlesseNtumble 
Well,later,I think this problem is unimportance.Because the game is sometimes crash instead always crash.So you can close this issue now.

**Comment by BlesseNtumble** [comment]
Check the configs of other add-ons, maybe you have a conflict of schematic page IDs
