### ISSUE TITLE
Issue with Dedicated Server

### ISSUE THREAD

**Issue by TheRealM18** [BlesseNtumble/GalaxySpace#264]
I currently am trying to get the current curse forge version to work with my Dedicated Server, and when i try to connect to it, it disconnects me.

[20:52:15] [Server thread/ERROR] [FML]: Exception caught during firing event asmodeuscore.core.event.RadiationEvent@3b402bb8:
java.lang.NoSuchMethodError: net.minecraft.entity.player.InventoryPlayer.func_70440_f(I)Lnet/minecraft/item/ItemStack;
	at galaxyspace.core.events.GSEventHandler.getProtectArmor(GSEventHandler.java:503) ~[GSEventHandler.class:?]
	at galaxyspace.core.events.GSEventHandler.onRadiation(GSEventHandler.java:451) ~[GSEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_393_GSEventHandler_onRadiation_RadiationEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at asmodeuscore.core.event.AsmodeusEvent.onEntityUpdate(AsmodeusEvent.java:73) [AsmodeusEvent.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_166_AsmodeusEvent_onEntityUpdate_LivingUpdateEvent.invoke(.dynamic) [?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:567) [ForgeHooks.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2088) [vp.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234) [aed.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382) [oq.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173) [pa.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209) [NetworkDispatcher$1.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) [gw.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [oz.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_192]
[20:52:15] [Server thread/ERROR] [FML]: Index: 1 Listeners:
[20:52:15] [Server thread/ERROR] [FML]: 0: NORMAL
[20:52:15] [Server thread/ERROR] [FML]: 1: ASM: galaxyspace.core.events.GSEventHandler@50e142eb onRadiation(Lasmodeuscore/core/event/RadiationEvent;)V
[20:52:15] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.entity.living.LivingEvent$LivingUpdateEvent@44dd8fb:
java.lang.NoSuchMethodError: net.minecraft.entity.player.InventoryPlayer.func_70440_f(I)Lnet/minecraft/item/ItemStack;
	at galaxyspace.core.events.GSEventHandler.getProtectArmor(GSEventHandler.java:503) ~[GSEventHandler.class:?]
	at galaxyspace.core.events.GSEventHandler.onRadiation(GSEventHandler.java:451) ~[GSEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_393_GSEventHandler_onRadiation_RadiationEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at asmodeuscore.core.event.AsmodeusEvent.onEntityUpdate(AsmodeusEvent.java:73) ~[AsmodeusEvent.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_166_AsmodeusEvent_onEntityUpdate_LivingUpdateEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:567) [ForgeHooks.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2088) [vp.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234) [aed.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382) [oq.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173) [pa.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209) [NetworkDispatcher$1.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) [gw.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [oz.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_192]
[20:52:15] [Server thread/ERROR] [FML]: Index: 3 Listeners:
[20:52:15] [Server thread/ERROR] [FML]: 0: NORMAL
[20:52:15] [Server thread/ERROR] [FML]: 1: ASM: class flaxbeard.immersivepetroleum.common.EventHandler test(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[20:52:15] [Server thread/ERROR] [FML]: 2: ASM: micdoodle8.mods.galacticraft.core.event.EventHandlerGC@494d58b7 entityLivingEvent(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[20:52:15] [Server thread/ERROR] [FML]: 3: ASM: asmodeuscore.core.event.AsmodeusEvent@6dc5d419 onEntityUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[20:52:15] [Server thread/ERROR] [FML]: 4: ASM: com.mjr.extraplanets.handlers.MainHandlerServer@5ba7961 onEntityUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[20:52:15] [Server thread/ERROR] [FML]: 5: ASM: galaxyspace.core.events.GSEventHandler@50e142eb onEntityUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[20:52:15] [Server thread/ERROR] [FML]: 6: ASM: com.mjr.planetprogression.handlers.MainHandlerServer@4c3874a3 onEntityUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[20:52:15] [Server thread/ERROR] [FML]: 7: ASM: blusunrize.immersiveengineering.common.EventHandler@31e6b091 onLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[20:52:15] [Server thread/ERROR] [FML]: 8: ASM: stevekung.mods.moreplanets.core.event.EntityEventHandler@665c0e08 onLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[20:52:15] [Server thread/ERROR] [FML]: 9: ASM: li.cil.oc.common.event.NanomachinesHandler$Common$@73aca938 onLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[20:52:15] [Server thread/ERROR] [FML]: 10: ASM: li.cil.oc.common.event.HoverBootsHandler$@a2267a6 onLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[20:52:15] [Server thread/WARN] [net.minecraft.network.NetworkSystem]: Failed to handle packet for /192.168.0.3:53972
net.minecraft.util.ReportedException: Ticking player
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:459) ~[oq.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173) ~[pa.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209) ~[NetworkDispatcher$1.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) ~[gw.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [oz.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_192]
Caused by: java.lang.NoSuchMethodError: net.minecraft.entity.player.InventoryPlayer.func_70440_f(I)Lnet/minecraft/item/ItemStack;
	at galaxyspace.core.events.GSEventHandler.getProtectArmor(GSEventHandler.java:503) ~[GSEventHandler.class:?]
	at galaxyspace.core.events.GSEventHandler.onRadiation(GSEventHandler.java:451) ~[GSEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_393_GSEventHandler_onRadiation_RadiationEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
	at asmodeuscore.core.event.AsmodeusEvent.onEntityUpdate(AsmodeusEvent.java:73) ~[AsmodeusEvent.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_166_AsmodeusEvent_onEntityUpdate_LivingUpdateEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:567) ~[ForgeHooks.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2088) ~[vp.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234) ~[aed.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382) ~[oq.class:?]
	... 9 more
[20:52:16] [Server thread/INFO] [net.minecraft.network.NetHandlerPlayServer]: TheRealM18 lost connection: Internal server error
[20:52:16] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: TheRealM18 left the game

**Comment by gxmy** [comment]
Is there anyway to work around this issue before the next version is released?

**Comment by Tiviacz1337** [comment]
When new version will come out?
