### ISSUE TITLE
AsmodeusCore  - Error Writing NBT 

### ISSUE THREAD

**Issue by sfxworks** [BlesseNtumble/GalaxySpace#276]
```
java.lang.NullPointerException
    at asmodeuscore.core.astronomy.dimension.world.gen.dungeons.standart.DungeonConfiguration.writeToNBT(DungeonConfiguration.java:51)
    at asmodeuscore.core.astronomy.dimension.world.gen.dungeons.standart.Piece.writeStructureToNBT(Piece.java:27)
    at asmodeuscore.core.astronomy.dimension.world.gen.dungeons.standart.DirectionalPiece.writeStructureToNBT(DirectionalPiece.java:38)
    at asmodeuscore.core.astronomy.dimension.world.gen.dungeons.standart.SizedPiece.writeStructureToNBT(SizedPiece.java:28)
    at net.minecraft.world.gen.structure.StructureComponent.createStructureBaseNBT(StructureComponent.java:54)
    at net.minecraft.world.gen.structure.StructureStart.writeStructureComponentsToNBT(StructureStart.java:79)
    at net.minecraft.world.gen.structure.MapGenStructure.setStructureStart(MapGenStructure.java:216)
    at net.minecraft.world.gen.structure.MapGenStructure.generateStructure(MapGenStructure.java:606)
    at micdoodle8.mods.galacticraft.planets.mars.world.gen.ChunkProviderMars.onPopulate(ChunkProviderMars.java:119)
    at micdoodle8.mods.galacticraft.api.prefab.world.gen.ChunkProviderSpace.populate(ChunkProviderSpace.java:362)
    at org.spongepowered.mod.world.gen.SpongeChunkGeneratorForge.populate(SpongeChunkGeneratorForge.java:269)
    at net.minecraft.world.chunk.Chunk.populate(Chunk.java:1019)
    at net.minecraft.world.chunk.Chunk.populate(Chunk.java:985)
    at net.minecraft.world.gen.ChunkProviderServer.provideChunk(ChunkProviderServer.java:157)
    at net.minecraft.server.management.PlayerChunkMapEntry.redirect$onProvidePlayerChunk$bei000(PlayerChunkMapEntry.java:1079)
    at net.minecraft.server.management.PlayerChunkMapEntry.providePlayerChunk(PlayerChunkMapEntry.java:126)
    at net.minecraft.server.management.PlayerChunkMap.tick(SourceFile:147)
    at net.minecraft.world.WorldServer.tick(WorldServer.java:227)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:756)
    at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:748)

```

Full crash report
https://pastebin.com/bpD4KxjG

Server side. Version info and mods in crash report.

**Comment by sfxworks** [comment]
Occurred again. Replicatable while users look for dungeons. 

We're using sponge's async lightning feature if that is a thing. 

https://pastebin.com/XZk8GapM
This is from the startup of latest.log. Looks like it's even having trouble reading it upon load.

**Comment by sfxworks** [comment]
3rd crash
https://pastebin.com/vNRjF6b4
I see your mod ontop of spongeforge's chunk generation in the stack trace. These two mods not compatible?

**Comment by BlesseNtumble** [comment]
https://yadi.sk/d/BUhNdj86M8i4zg
try it build

**Comment by sfxworks** [comment]
![image](https://user-images.githubusercontent.com/5921035/50732768-9a47dc00-114f-11e9-8ab7-3277a034bfbd.png)
Looks good. Generating chunks works just fine now. No crashes to report (except for the rocket at the end when I ran out of fuel and crashed back onto mars :) 

Push to curse and ill role it out in my pack asap!

**Comment by BlesseNtumble** [comment]
It's good news....
Please, check generation dungeons on Mars, Ceres and Io.

**Comment by sfxworks** [comment]
Don't know how related this is, but when going to these malformed dungeons (that don't cause crashes for some reason that much anymore) there was no Tier 3 schematic set in the chest. The only other related mod that seems to be messing with loot tables is planet progressions. However, it seems it just adds an item. (This is still for v0.0.4)

Credit to xA5 for finding this. He's also been to 35 dungeons and it still hasn't spawned in the chest. I was blaming the RNG at first, but this seems odd.
https://github.com/MJRLegends/Planet-Progression/blob/1ee9348adf2bcbd8bb274e6a97bccaf8fa6f4659/src/main/java/com/mjr/planetprogression/handlers/MainHandlerServer.java#L161

I also just spotted DungeonConfiguration in the first bit of the stacktrace.
`asmodeuscore.core.astronomy.dimension.world.gen.dungeons.standart.DungeonConfiguration.writeToNBT(DungeonConfiguration.java:51)`

**Comment by BlesseNtumble** [comment]
Schematic tier 3 is delete.
See the new craft rocket tier 3 in JEI.

**Comment by Blayyke** [comment]
The issue is that none of the schematics from GalaxySpace are spawning. I (xA5) have been playing on the Lapito's Galacticraft modpack server and have not found a single schematic from GalaxySpace, only astro miner and cargo rocket schematics in the 35+ dungeons I've finished. The server frequently crashed as I was exploring mars with the errors posted above.

**Comment by sfxworks** [comment]
> Schematic tier 3 is delete.


GSpace Schematics are not spawning is what I meant.

**Comment by BlesseNtumble** [comment]
Schematic Box on Mars and Ceres.

**Comment by Blayyke** [comment]
How hard are these to get? I haven't found a single one in what is approaching 40 dungeons now.

**Comment by BlesseNtumble** [comment]
GalacticraftRegistry.getDungeonLoot(2).clear();
GalacticraftRegistry.addDungeonLoot(2, new ItemStack(MarsItems.schematic, 1, 1));	    
GalacticraftRegistry.addDungeonLoot(2, new ItemStack(MarsItems.schematic, 1, 2));
GalacticraftRegistry.addDungeonLoot(2, new ItemStack(GSItems.SCHEMATICS, 1, 5));
GalacticraftRegistry.addDungeonLoot(2, new ItemStack(GSItems.BASIC, 1, 10)); <- Schematic Box

1 / 4 = 0.(25) %

**Comment by Blayyke** [comment]
Hm, I'll continue testing and report back if I cannot find any after another 10-20 dungeons.

**Comment by Blayyke** [comment]
After even more testing in a plain environment with no mods other than GalaxySpace and Galacticraft, I cannot find any schematic boxes and only can find the Astro Miner and Cargo rocket schematic.

**Comment by BlesseNtumble** [comment]
I will add schematic box on Moon.

**Comment by Blayyke** [comment]
Sorry if i understand  this wrong, but the issue is that the schematic box wont spawn on mars not that it isnt on moon.

**Comment by sfxworks** [comment]
This is great to hear. We thank you for the fix. However, we are still stuck with a dilemma to where we are unable to have this version on curse. So we can not distribute it to our players. We would like to know, when are you able to release this?
![image](https://user-images.githubusercontent.com/5921035/50897226-7bf51100-13d9-11e9-9713-8063ee0ae2c0.png)

**Comment by BlesseNtumble** [comment]
already on curse.

**Comment by Blayyke** [comment]
it is not on curse as of this moment.

**Comment by Blayyke** [comment]
nevermind that, asmodeus core has an update. was looking at galaxyspace.

**Comment by sfxworks** [comment]
Please re-open this issue. We are now getting random crashes.

```
Time: 1/12/19 11:40 PM
Description: Exception ticking world

java.lang.NullPointerException: Exception ticking world
        at asmodeuscore.core.astronomy.dimension.world.gen.dungeons.standart.DungeonConfiguration.writeToNBT(DungeonConfiguration.java:67)
        at asmodeuscore.core.astronomy.dimension.world.gen.dungeons.standart.Piece.func_143012_a(Piece.java:27)
        at asmodeuscore.core.astronomy.dimension.world.gen.dungeons.standart.DirectionalPiece.func_143012_a(DirectionalPiece.java:38)
        at asmodeuscore.core.astronomy.dimension.world.gen.dungeons.standart.SizedPiece.func_143012_a(SizedPiece.java:28)
        at net.minecraft.world.gen.structure.StructureComponent.func_143010_b(StructureComponent.java:54)
        at net.minecraft.world.gen.structure.StructureStart.func_143021_a(StructureStart.java:79)
        at net.minecraft.world.gen.structure.MapGenStructure.func_143026_a(MapGenStructure.java:216)
        at net.minecraft.world.gen.structure.MapGenStructure.func_175794_a(MapGenStructure.java:606)
        at micdoodle8.mods.galacticraft.planets.mars.world.gen.ChunkProviderMars.onPopulate(ChunkProviderMars.java:119)
        at micdoodle8.mods.galacticraft.api.prefab.world.gen.ChunkProviderSpace.func_185931_b(ChunkProviderSpace.java:362)
        at org.spongepowered.mod.world.gen.SpongeChunkGeneratorForge.func_185931_b(SpongeChunkGeneratorForge.java:269)
        at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1019)
        at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:999)
        at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
        at net.minecraft.server.management.PlayerChunkMapEntry.redirect$onProvidePlayerChunk$bdo000(PlayerChunkMapEntry.java:1079)
        at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126)
        at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:147)
        at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
        at java.lang.Thread.run(Thread.java:748)
```

Full crash report at https://pastebin.com/2S0ZKZHH

**Comment by Nbgreen** [comment]
Here are 6 crashes caused by it today alone

https://paste.dimdev.org/tepuniyigo.sql
https://paste.dimdev.org/ogobixuroz.sql
https://paste.dimdev.org/laqocufema.sql
https://paste.dimdev.org/ituhazomig.sql
https://paste.dimdev.org/oxasadahav.sql
https://paste.dimdev.org/wakekivijo.sql

**Comment by BlesseNtumble** [comment]
Fixed
