### ISSUE TITLE
Crashing on controls menu

### ISSUE THREAD

**Issue by Jonah-Lazer** [BlesseNtumble/GalaxySpace#292]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version:1.7.10
2. Galacticraft version:3
3. GalaxySpace version:1.2.9
4. AsmodeusCore version (for 2.0.1 version and above): 
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)):

------------------------------------------------------------------------
Description of the issue: whenever I go into the controls menu, the game crashes

------------------------------------------------------------------------
Screenshot/Video:
![Minecraft Launcher 3_30_2019 3_06_24 PM](https://user-images.githubusercontent.com/49106122/55281676-74207b00-52fd-11e9-8124-2c20699cd693.png)

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):
[crash-2019-03-30_15.06.13-client.txt](https://github.com/BlesseNtumble/GalaxySpace/files/3025960/crash-2019-03-30_15.06.13-client.txt)

------------------------------------------------------------------------

**Comment by CanisArtorus** [comment]
mc: 1.7.10
GC: 3.0.12.504
GS: 1.2.9
SSP

Agreed.  Client crash on opening the Options-Controls menu. 
New in today's version, 1.2.8 works fine.

[crash-2019-03-30_23.30.32-client.txt](https://github.com/BlesseNtumble/GalaxySpace/files/3026243/crash-2019-03-30_23.30.32-client.txt)

From latest.log 
[...]
[23:30:05] [Client thread/INFO]: com.dyonovan.tcnodetracker.gui.GuiMain
[23:30:19] [Server thread/INFO]: Saving and pausing game...
[23:30:20] [Client thread/INFO]: net.minecraft.client.gui.GuiIngameMenu
[23:30:20] [Server thread/INFO]: Saving chunks for level 'Mysterious'/Overworld
...
[23:30:21] [Server thread/INFO]: Saving chunks for level 'Mysterious'/Pluto
[23:30:28] [Client thread/INFO]: Mapping halted in C:\DevApps\Curse\Instances\Gregorious hexii Artorus\journeymap\data\sp\Mysterious-\DIM0
[23:30:29] [Server thread/INFO]: Stopping server
[23:30:29] [Server thread/INFO]: Saving players
[23:30:29] [Server thread/INFO]: Saving worlds
[23:30:29] [Server thread/INFO]: Saving chunks for level 'Mysterious'/Overworld
[23:30:29] [Netty Client IO #0/INFO]: Restoring client configs.
[23:30:29] [Netty Client IO #0/INFO]: Reset configs to client values for com.enderio.core.common.config.ConfigHandler
[23:30:29] [Netty Client IO #0/INFO]: Reset configs to client values for tterrag.wailaplugins.config.WPConfigHandler
[23:30:29] [Server thread/INFO]: Saving chunks for level 'Mysterious'/Nether
...
[23:30:29] [Server thread/INFO]: Saving chunks for level 'Mysterious'/Pluto
[23:30:29] [Server thread/INFO]: Unloading dimension 0
...
[23:30:29] [Server thread/INFO]: Unloading dimension -1008
[23:30:32] [Client thread/FATAL]: Reported exception thrown!
net.minecraft.util.ReportedException: Rendering screen
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1092) ~[blt.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001) ~[bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_181]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NullPointerException
	at net.minecraft.client.gui.GuiListExtended.func_148181_b(SourceFile:53) ~[bch.class:?]
	at net.minecraft.client.gui.GuiControls.func_146286_b(SourceFile:81) ~[bew.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:306) ~[bdw.class:?]
	at net.minecraft.client.gui.GuiSlot.func_148128_a(GuiSlot.java:270) ~[bcm.class:?]
	at net.minecraft.client.gui.GuiControls.func_73863_a(SourceFile:107) ~[bew.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061) ~[blt.class:?]
	... 9 more
[23:30:32] [Client thread/INFO]: [net.minecraft.client.Minecraft:func_71377_b:349]: ---- Minecraft Crash Report ----
[...]

**Comment by BlesseNtumble** [comment]
Download 1.2.10 and try.
