### ISSUE TITLE
Rockets..mostly

### ISSUE THREAD

**Issue by dazedtracers** [BlesseNtumble/GalaxySpace#301]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: 1.12.2-forge1.12.2-14.23.5.2768
2. Galacticraft version: 4.0.2.190
3. GalaxySpace version: 2.0.1 STABLE (2.0.7)
4. AsmodeusCore version (for 2.0.1 version and above): 0.0.3 (0.0.7)
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): SpongeForge(b2768), also tested in SSP

------------------------------------------------------------------------
Description of the issue:
Launch controller won't work with advanced(5x5) pad. T6 rocket lose sublight capability when hand/weapon broken for placement elsewhere. Hand broken sublight capable rocket can no longer edit sublight capability in modification table(remove/reinstall would be easy workaround, cannot even add anew) Duplicate rocket in lander when sublight capability not broken. Duplicate rocket retains sublight capability..rocket w/o sublight and pad in typical slots(lander)

Prior release(2.0.6) had issue(crash server on chunk load) with oxygen storage cluster, haven't tested again w latest. Happy to see blaze boss fixed..will retest that soon as well.

------------------------------------------------------------------------
Screenshot/Video:

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):

------------------------------------------------------------------------

**Comment by dazedtracers** [comment]
Duplicate rocket retains sublight capability..rocket w/o sublight and pad in typical slots

**Comment by dazedtracers** [comment]
"Advanced Oxygen Module" rather..fails chunk. Didn't actually reboot to see if it crashed server as previously experienced, my guess is that it would as it simply wouldn't load the chunk until I /setblock replaced it w air.

07.04 15:58:51 [Server] Server thread/ERROR [FML]: A TileEntity type galaxyspace.systems.SolarSystem.planets.overworld.tile.TileEntityOxygenStorageModule has throw an exception trying to write state. It will not persist. Report this to the mod author
07.04 15:58:51 [Server] INFO java.lang.RuntimeException: class galaxyspace.systems.SolarSystem.planets.overworld.tile.TileEntityOxygenStorageModule is missing a mapping! This is a bug!
07.04 15:58:51 [Server] INFO at net.minecraft.tileentity.TileEntity.func_189516_d(TileEntity.java:78) ~[avj.class:?]
07.04 15:58:51 [Server] INFO at net.minecraft.tileentity.TileEntity.func_189515_b(TileEntity.java:69) ~[avj.class:?]
07.04 15:58:51 [Server] INFO at micdoodle8.mods.galacticraft.core.energy.tile.EnergyStorageTile.func_189515_b(EnergyStorageTile.java:36) ~[EnergyStorageTile.class:?]
07.04 15:58:51 [Server] INFO at micdoodle8.mods.galacticraft.core.energy.tile.TileBaseUniversalElectrical.func_189515_b(TileBaseUniversalElectrical.java:179) ~[TileBaseUniversalElectrical.class:?]
07.04 15:58:51 [Server] INFO at micdoodle8.mods.galacticraft.core.energy.tile.TileBaseElectricBlock.func_189515_b(TileBaseElectricBlock.java:148) ~[TileBaseElectricBlock.class:?]
07.04 15:58:51 [Server] INFO at micdoodle8.mods.galacticraft.core.tile.TileEntityOxygen.func_189515_b(TileEntityOxygen.java:136) ~[TileEntityOxygen.class:?]
07.04 15:58:51 [Server] INFO at galaxyspace.systems.SolarSystem.planets.overworld.tile.TileEntityOxygenStorageModule.func_189515_b(TileEntityOxygenStorageModule.java:93) ~[TileEntityOxygenStorageModule.class:?]
07.04 15:58:51 [Server] INFO at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunkLoader.java:382) [aye.class:?]
07.04 15:58:51 [Server] INFO at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:173) [aye.class:?]
07.04 15:58:51 [Server] INFO at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:202) [on.class:?]
07.04 15:58:51 [Server] INFO at net.minecraft.world.gen.ChunkProviderServer.func_186027_a(ChunkProviderServer.java:230) [on.class:?]
07.04 15:58:51 [Server] INFO at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:2452) [oo.class:?]
07.04 15:58:51 [Server] INFO at org.spongepowered.common.world.WorldManager.saveWorld(WorldManager.java:542) [WorldManager.class:1.12.2-2768-7.1.5]
07.04 15:58:51 [Server] INFO at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:3892) [MinecraftServer.class:?]
07.04 15:58:51 [Server] INFO at net.minecraft.server.MinecraftServer.constant$getSaveTickInterval$zjm000(MinecraftServer.java:3845) [MinecraftServer.class:?]
07.04 15:58:51 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:687) [MinecraftServer.class:?]
07.04 15:58:51 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
07.04 15:58:51 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_162]

Indeed happy blaze boss no longer crashes server on death, gg :)
