### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by liopard** [BlesseNtumble/GalaxySpace#453]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: 1.12.2
2. Galacticraft version : 4.0.2.272
3. GalaxySpace version: 2.0.13
4. AsmodeusCore version (for 2.0.1 version and above):  0.0.16
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): SSP
6. Other add-ons: 
------------------------------------------------------------------------
Description of the issue:

------------------------------------------------------------------------
Screenshot/Video:

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):
---- Minecraft Crash Report ----

WARNING: coremods are present:
  GSHooksLoader (GalaxySpace-1.12.2-2.0.13.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.272.jar)
Contact their authors BEFORE contacting forge

// Ouch. That hurt :(

Time: 6/4/20 2:05 PM
Description: Unexpected error

java.lang.ArrayIndexOutOfBoundsException: 56
	at net.minecraft.world.chunk.Chunk.func_177413_a(Chunk.java:644)
	at asmodeuscore.core.handler.ProviderFogHandler.onRenderFog(ProviderFogHandler.java:107)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_96_ProviderFogHandler_onRenderFog_RenderFogEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.client.ForgeHooksClient.onFogRender(ForgeHooksClient.java:409)
	at sun.reflect.GeneratedMethodAccessor48.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:660)
	at net.minecraft.client.renderer.EntityRenderer.func_78468_a(EntityRenderer.java:2679)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1680)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1613)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1384)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.world.chunk.Chunk.func_177413_a(Chunk.java:644)
	at asmodeuscore.core.handler.ProviderFogHandler.onRenderFog(ProviderFogHandler.java:107)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_96_ProviderFogHandler_onRenderFog_RenderFogEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.client.ForgeHooksClient.onFogRender(ForgeHooksClient.java:409)
	at sun.reflect.GeneratedMethodAccessor48.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:660)
	at net.minecraft.client.renderer.EntityRenderer.func_78468_a(EntityRenderer.java:2679)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1680)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1613)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [GCEntityClientPlayerMP['rigkid'/2040, l='MpServer', x=-117.00, y=900.00, z=41.00]]
	Chunk stats: MultiplayerChunkCache: 1, 1
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-117,64,41), Chunk: (at 11,4,9 in -8,2; contains blocks -128,0,32 to -113,255,47), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 29389 game time, 19469 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 2 total; [EntityLander['Посадочный модуль'/2632, l='MpServer', x=-117.00, y=900.00, z=41.00], GCEntityClientPlayerMP['rigkid'/2040, l='MpServer', x=-117.00, y=900.00, z=41.00]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:427)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 519075544 bytes (495 MB) / 1130962944 bytes (1078 MB) up to 2083782656 bytes (1987 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2000m -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 1, tcache: 12, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 Optifine OptiFine_1.12.2_HD_U_E3 15 mods loaded, 15 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                  | Version      | Source                                    | Signature                                |
	|:------ |:------------------- |:------------ |:----------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft           | 1.12.2       | minecraft.jar                             | None                                     |
	| LCHIJA | mcp                 | 9.42         | minecraft.jar                             | None                                     |
	| LCHIJA | FML                 | 8.0.99.99    | forge-1.12.2-14.23.5.2847.jar             | None                                     |
	| LCHIJA | forge               | 14.23.5.2847 | forge-1.12.2-14.23.5.2847.jar             | None                                     |
	| LCHIJA | micdoodlecore       |              | minecraft.jar                             | None                                     |
	| LCHIJA | galacticraftcore    | 4.0.2.272    | GalacticraftCore-1.12.2-4.0.2.272.jar     | None                                     |
	| LCHIJA | galacticraftplanets | 4.0.2.272    | Galacticraft-Planets-1.12.2-4.0.2.272.jar | None                                     |
	| LCHIJA | asmodeuscore        | 0.0.14       | AsmodeusCore-1.12.2-0.0.14.jar            | None                                     |
	| LCHIJA | galaxyspace         | 2.0.13       | GalaxySpace-1.12.2-2.0.13.jar             | None                                     |
	| LCHIJA | waila               | 1.8.26       | Hwyla-1.8.26-B41_1.12.2.jar               | None                                     |
	| LCHIJA | jei                 | 4.15.0.291   | jei_1.12.2-4.15.0.291.jar                 | None                                     |
	| LCHIJA | oreexcavation       | 1.4.140      | OreExcavation-1.4.140.jar                 | None                                     |
	| LCHIJA | wailaharvestability | 1.1.12       | WailaHarvestability-mc1.12-1.1.12.jar     | None                                     |
	| LCHIJA | wawla               | 2.5.273      | Wawla-1.12.2-2.5.273.jar                  | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | xaeroworldmap       | 1.4.10.1     | XaerosWorldMap_1.4.10.1_Forge_1.12.jar    | None                                     |

	Loaded coremods (and transformers): 
GSHooksLoader (GalaxySpace-1.12.2-2.0.13.jar)
  galaxyspace.core.hooklib.minecraft.PrimaryClassTransformer
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.272.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.2.0' Renderer: 'GeForce GT 540M/PCI/SSE2'
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2847
	LWJGL: 2.9.4
	OpenGL: GeForce GT 540M/PCI/SSE2 GL version 4.2.0, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: Русский (Россия)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i3-2330M CPU @ 2.20GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_E3
	OptiFine Build: 20181210-121000
	Render Distance Chunks: 7
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.2.0
	OpenGlRenderer: GeForce GT 540M/PCI/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4
------------------------------------------------------------------------

**Comment by BlesseNtumble** [comment]
Download AsmodeusCore 0.0.15

**Comment by melody-rs** [comment]
This still happens with 0.0.15? #448 has the same error and is running 0.0.15
