### ISSUE TITLE
Europa Glitch and Crash

### ISSUE THREAD

**Issue by Abafar** [BlesseNtumble/GalaxySpace#497]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: 1.12.2
2. Galacticraft version: 1.12.2-4.0.2.280
3. GalaxySpace version: 1.12.2-2.0.14
4. AsmodeusCore version (for 2.0.1 version and above): 1.12.2-0.0.19
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): Singleplayer
6. Other add-ons: More Planets v1.12.2-2.0.24-GC251
------------------------------------------------------------------------
Description of the issue:
When trying to get to Europa, I was unable to leave the landing craft, and when I did, only one chunk would load, and the game would promptly crash. Tried three more times, and was still unable to do so. Video attached shows most recent attempt.

------------------------------------------------------------------------
Screenshot/Video:
https://kapwi.ng/c/ezkyFKoP
**AUDIO WARNING AT VERY END** crash causes the audio to freak out

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):

------------------------------------------------------------------------

**Comment by CaveJohnson376** [comment]
Send crash-report and/or logs, video won't do anything

**Comment by Abafar** [comment]
Apologies, here's a gif of it. It cuts off spontaneously due to crash
![Europa Glitch](https://user-images.githubusercontent.com/70295528/91399080-f23ec500-e802-11ea-9b6b-9fc36ccef258.gif)

**Comment by CaveJohnson376** [comment]
I've asked for crash-report or logs text file, not the screenhots/gifs/videos/anything :facepalm:

**Comment by Abafar** [comment]
Oh jeez, totally misread, I'm so sorry! Here's the crash report:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.280.jar)
  GSHooksLoader (GalaxySpace-1.12.2-2.0.14.jar)
  XaeroMinimapPlugin (Xaeros_Minimap_20.20.2_Forge_1.12.jar)
Contact their authors BEFORE contacting forge

// Don't be sad, have a hug! <3

Time: 8/28/20 10:45 PM
Description: Exception ticking world

java.lang.NoClassDefFoundError: net/minecraft/world/World$2
	at net.minecraft.world.World.func_190524_a(World.java:557)
	at net.minecraft.world.World.func_175685_c(World.java:493)
	at net.minecraft.world.World.func_175722_b(World.java:440)
	at net.minecraft.world.World.markAndNotifyBlock(World.java:381)
	at net.minecraft.world.World.func_180501_a(World.java:361)
	at net.minecraft.world.World.func_175656_a(World.java:425)
	at galaxyspace.systems.SolarSystem.moons.europa.world.gen.BiomeDecoratorEuropa.decorate(BiomeDecoratorEuropa.java:64)
	at micdoodle8.mods.galacticraft.api.prefab.world.gen.BiomeDecoratorSpace.decorate(BiomeDecoratorSpace.java:42)
	at asmodeuscore.core.astronomy.dimension.world.gen.ChunkProviderSpaceLakes.decoratePlanet(ChunkProviderSpaceLakes.java:671)
	at asmodeuscore.core.astronomy.dimension.world.gen.ChunkProviderSpaceLakes.func_185931_b(ChunkProviderSpaceLakes.java:664)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1019)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:990)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:147)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.world.World.func_190524_a(World.java:557)
	at net.minecraft.world.World.func_175685_c(World.java:493)
	at net.minecraft.world.World.func_175722_b(World.java:440)
	at net.minecraft.world.World.markAndNotifyBlock(World.java:381)
	at net.minecraft.world.World.func_180501_a(World.java:361)
	at net.minecraft.world.World.func_175656_a(World.java:425)
	at galaxyspace.systems.SolarSystem.moons.europa.world.gen.BiomeDecoratorEuropa.decorate(BiomeDecoratorEuropa.java:64)
	at micdoodle8.mods.galacticraft.api.prefab.world.gen.BiomeDecoratorSpace.decorate(BiomeDecoratorSpace.java:42)
	at asmodeuscore.core.astronomy.dimension.world.gen.ChunkProviderSpaceLakes.decoratePlanet(ChunkProviderSpaceLakes.java:671)
	at asmodeuscore.core.astronomy.dimension.world.gen.ChunkProviderSpaceLakes.func_185931_b(ChunkProviderSpaceLakes.java:664)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1019)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:990)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:147)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227)

-- Affected level --
Details:
	Level name: New World
	All players: 1 total; [GCEntityPlayerMP['Abafar'/1811, l='New World', x=-373.50, y=901.90, z=1422.50]]
	Chunk stats: ServerChunkCache: 81 Drop: 0
	Level seed: -5127541442909625876
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1199311624 bytes (1143 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 1, tcache: 12, allocated: 0, tallocated: 0
	FML: ~~ERROR~~ NoClassDefFoundError: net/minecraftforge/common/util/TextTable$1
	Loaded coremods (and transformers): 
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.280.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
GSHooksLoader (GalaxySpace-1.12.2-2.0.14.jar)
  galaxyspace.core.hooklib.minecraft.PrimaryClassTransformer
XaeroMinimapPlugin (Xaeros_Minimap_20.20.2_Forge_1.12.jar)
  xaero.common.core.transformer.ChunkTransformer
  xaero.common.core.transformer.NetHandlerPlayClientTransformer
  xaero.common.core.transformer.EntityPlayerTransformer
  xaero.common.core.transformer.AbstractClientPlayerTransformer
  xaero.common.core.transformer.WorldClientTransformer
  xaero.common.core.transformer.EntityPlayerSPTransformer
  xaero.common.core.transformer.PlayerListTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [GCEntityPlayerMP['Abafar'/1811, l='New World', x=-373.50, y=901.90, z=1422.50]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by CaveJohnson376** [comment]
Pls do not send crash-reports like that. Either put it into `code block` or upload it as file or at [pastebin](pastebin.com).

**Comment by mMONTAGEe** [comment]
Paste your crashlog here. not comments haste.romvoid.dev

**Comment by Invulnerable23** [comment]
I have **exactly** the same situation. Because of this bug, I can't do anything on Europe, everything is crashing. Please help us with the bug.
My log on Pastebin: https://pastebin.com/7wxhVGFf 
Thank you in advance

**Comment by BlesseNtumble** [comment]
Fixed in 2.0.15
