### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by RockIsLife** [BlesseNtumble/GalaxySpace#53]
---- Minecraft Crash Report ----
// Oops.

Time: 12.05.16 10:43
Description: Exception in server tick loop

cpw.mods.fml.common.LoaderException: java.lang.NoSuchFieldError: textures
    at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
    at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:559)
    at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:88)
    at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:319)
    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:176)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:631)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoSuchFieldError: textures
    at galaxyspace.SolarSystem.planets.mercury.blocks.MercuryBlocks.<init>(MercuryBlocks.java:32)
    at galaxyspace.SolarSystem.core.registers.blocks.GSBlocks.initialize(GSBlocks.java:151)
    at galaxyspace.GalaxySpace.preInit(GalaxySpace.java:164)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
    at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556)
    ... 5 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.7.10
    KCauldron Version: pw.prok:KCauldron:1.7.10-1492.152
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_77, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 92107232 bytes (87 MB) / 259522560 bytes (247 MB) up to 4260102144 bytes (4062 MB)
    JVM Flags: 2 total; -Xincgc -Xmx4G
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1492 37 mods loaded, 37 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCH mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UCH FML{7.10.99.99} [Forge Mod Loader](spigot.jar) 
    UCH Forge{10.13.4.1492} [Minecraft Forge](spigot.jar) 
    UCH kimagine{0.1} [KImagine](minecraft.jar) 
    UCH appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core](minecraft.jar) 
    UCH CodeChickenCore{1.0.6.39} [CodeChicken Core](minecraft.jar) 
    UCH Micdoodlecore{} [Micdoodle8 Core](minecraft.jar) 
    UCH MobiusCore{1.2.5} [MobiusCore](minecraft.jar) 
    UCH NotEnoughItems{1.0.4.100} [Not Enough Items](NotEnoughItems-1.7.10-1.0.4.100-universal.jar) 
    UCH appliedenergistics2{rv2-stable-10} [Applied Energistics 2](appliedenergistics2-rv2-stable-10.jar) 
    UCH mod_AsyncWorldEdit_Injector{2.1.0} [AsyncWorldEdit Injector](AsyncWorldEditInjector.jar) 
    UCH BiblioCraft{1.10.4} [BiblioCraft](BiblioCraft[v1.10.4][MC1.7.10].jar) 
    UCH BuildCraft|Core{7.1.16} [BuildCraft](buildcraft-7.1.16.jar) 
    UCH BuildCraft|Builders{7.1.16} [BC Builders](buildcraft-7.1.16.jar) 
    UCH BuildCraft|Transport{7.1.16} [BC Transport](buildcraft-7.1.16.jar) 
    UCH BuildCraft|Energy{7.1.16} [BC Energy](buildcraft-7.1.16.jar) 
    UCH BuildCraft|Silicon{7.1.16} [BC Silicon](buildcraft-7.1.16.jar) 
    UCH BuildCraft|Robotics{7.1.16} [BC Robotics](buildcraft-7.1.16.jar) 
    UCH BuildCraft|Factory{7.1.16} [BC Factory](buildcraft-7.1.16.jar) 
    UCH chisel{2.5.1.a790281} [Chisel 2](Chisel2-2.5.1.a790281.jar) 
    UCH ChunkPurge{2.1} [Chunk Purge](ChunkPurge-1.7.10-2.1.jar) 
    UCH customnpcs{1.7.10d} [CustomNpcs](CustomNPCs_1.7.10d.jar) 
    UCH DragonsRadioMod{1.6.3} [Dragon's Radio Mod](DragonsRadioMod-MC1.7.10-1.6.3.jar) 
    UCH EventHelper{1.6} [EventHelper](EventHelper-1.6.jar) 
    UCH IC2{2.2.820-experimental} [IndustrialCraft 2](industrialcraft-2-2.2.820-experimental.jar) 
    UCH GalacticraftCore{3.0.12} [Galacticraft Core](GalacticraftCore-1.7-3.0.12.460.jar) 
    UCH GalacticraftMars{3.0.12} [Galacticraft Planets](Galacticraft-Planets-1.7-3.0.12.460.jar) 
    UCE GalaxySpace{1.0.9} [GalaxySpace](GalaxySpace-1.0.9 STABLE.jar) 
    UCH GraviSuite{1.7.10-2.0.3} [Graviation Suite](GraviSuite-1.7.10-2.0.3.jar) 
    UCH IC2LaserFix{2.0} [IC2 Laser Fix](IC2LaserFix-1.7.10.jar) 
    UCH IC2NuclearControl{2.3.3a-Exist} [Nuclear Control 2](IC2NuclearControl-2.3.3a-Exist.jar) 
    UCH IronChest{6.0.62.742} [Iron Chest](ironchest-1.7.10-6.0.62.742-universal.jar) 
    UCH MarketCompanion{2.0.0} [MarketCompanion](MarketCompanion-1.7.10-2.0.1.jar) 
    UCH MineTweaker3{3.0.10} [MineTweaker 3](MineTweaker3-1.7.10-3.0.10B.jar) 
    UCH MapWriter{2.1.2} [MapWriter](Opis-1.2.5_1.7.10.jar) 
    UCH Opis{1.2.5} [Opis](Opis-1.2.5_1.7.10.jar) 
    UCH worldedit{6.0-beta-01} [WorldEdit](worldedit-forge-mc1.7.10-6.0-beta-01.jar) 
    AE2 Version: stable rv2-stable-10 for Forge 10.13.2.1291
    Profiler Position: N/A (disabled)
    Is Modded: Definitely; Server brand changed to 'kcauldron,cauldron,craftbukkit,mcpc,fml,forge'
    Type: Dedicated Server (map_server.txt)

**Comment by JrantKing** [comment]
the same error

**Comment by JrantKing** [comment]
server error

**Comment by BlesseNtumble** [comment]
update forge

**Comment by JeanlucFranklin** [comment]
I am getting a similar error however I am using the newest version of forge.
http://pastebin.com/raw/QAVjzg3r
Only on the server like Jrant said
The client side is working fine.

**Comment by JrantKing** [comment]
my forge ver 1614

**Comment by BlesseNtumble** [comment]
@JrantKing FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1492

Fixed. Redownload version.
