### ISSUE TITLE
Can not enter Barnarda C and Proxima B

### ISSUE THREAD

**Issue by willis1030** [BlesseNtumble/GalaxySpace#556]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version:
2. Galacticraft version:
3. GalaxySpace version:
4. AsmodeusCore version (for 2.0.1 version and above): 
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)):
6. Other add-ons:
------------------------------------------------------------------------
Description of the issue:

1.minecraft forge1.12.2-14.23.5.2855.
2.GalacticraftCore-1.12.2-4.0.2.280 Galacticraft-Planets-1.12.2-4.0.2.280 MicdoodleCore-1.12.2-4.0.2.280.
3.GalaxySpace-1.12.2-2.0.17.
4.AsmodeusCore-1.12.2-0.0.27.
5.both single and multiple player tested.
6.with no other addons and with others like immersiveengineering are the same bug.

------------------------------------------------------------------------
Screenshot/Video:

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):

---- Minecraft Crash Report ----

WARNING: coremods are present:
  GSHooksLoader (GalaxySpace-1.12.2-2.0.17.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.280.jar)
Contact their authors BEFORE contacting forge

// You should try our sister game, Minceraft!

Time: 11/7/21 11:37 AM
Description: Ticking player

java.lang.NullPointerException: Ticking player
	at asmodeuscore.core.event.AsmodeusEvent.doPressureForEntity(AsmodeusEvent.java:209)
	at asmodeuscore.core.event.AsmodeusEvent.onEntityUpdate(AsmodeusEvent.java:154)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_94_AsmodeusEvent_onEntityUpdate_LivingUpdateEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:581)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2095)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234)
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382)
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at asmodeuscore.core.event.AsmodeusEvent.doPressureForEntity(AsmodeusEvent.java:209)
	at asmodeuscore.core.event.AsmodeusEvent.onEntityUpdate(AsmodeusEvent.java:154)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_94_AsmodeusEvent_onEntityUpdate_LivingUpdateEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:581)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2095)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234)

-- Player being ticked --
Details:
	Entity Type: null (micdoodle8.mods.galacticraft.core.entities.player.GCEntityPlayerMP)
	Entity ID: 1531
	Entity Name: willis97
	Entity's Exact location: -125.50, 900.00, 289.50
	Entity's Block location: World: (-126,900,289), Chunk: (at 2,56,1 in -8,18; contains blocks -128,0,288 to -113,255,303), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: EntityLander['登陸艙'/207334, l='新的世界', x=-125.50, y=900.00, z=289.50]
Stacktrace:
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382)
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@35ecaac7
Stacktrace:
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1453009152 bytes (1385 MB) / 2181038080 bytes (2080 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 4, tallocated: 76
	FML: MCP 9.42 Powered by Forge 14.23.5.2855 9 mods loaded, 9 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                  | Version      | Source                                    | Signature                                |
	|:------ |:------------------- |:------------ |:----------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft           | 1.12.2       | minecraft.jar                             | None                                     |
	| LCHIJA | mcp                 | 9.42         | minecraft.jar                             | None                                     |
	| LCHIJA | FML                 | 8.0.99.99    | forge-1.12.2-14.23.5.2855.jar             | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge               | 14.23.5.2855 | forge-1.12.2-14.23.5.2855.jar             | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | micdoodlecore       |              | minecraft.jar                             | None                                     |
	| LCHIJA | galacticraftcore    | 4.0.2.280    | GalacticraftCore-1.12.2-4.0.2.280.jar     | None                                     |
	| LCHIJA | galacticraftplanets | 4.0.2.280    | Galacticraft-Planets-1.12.2-4.0.2.280.jar | None                                     |
	| LCHIJA | asmodeuscore        | 0.0.27       | AsmodeusCore-1.12.2-0.0.27.jar            | None                                     |
	| LCHIJA | galaxyspace         | 2.0.17       | GalaxySpace-1.12.2-2.0.17.jar             | None                                     |

	Loaded coremods (and transformers): 
GSHooksLoader (GalaxySpace-1.12.2-2.0.17.jar)
  galaxyspace.core.hooklib.minecraft.PrimaryClassTransformer
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.280.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [GCEntityPlayerMP['willis97'/1531, l='新的世界', x=-125.50, y=900.00, z=289.50]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

------------------------------------------------------------------------

**Comment by BlesseNtumble** [comment]
Donwload AsmodeusCore 0.0.28
