### ISSUE TITLE
Issue with Dedicated server

### ISSUE THREAD

**Issue by The-Silver-Kitsune** [BlesseNtumble/GalaxySpace#6]
`---- Minecraft Crash Report ----
// I let you down. Sorry :(
Time: 2/18/16 5:59 PM
Description: Exception in server tick loop
cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: net/minecraft/client/entity/EntityClientPlayerMP
at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:559)
at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:88)
at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:314)
at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:117)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/entity/EntityClientPlayerMP
at galaxyspace.GalaxySpace.preInit(GalaxySpace.java:165)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
at com.google.common.eventbus.EventBus.post(EventBus.java:275)
at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
at com.google.common.eventbus.EventBus.post(EventBus.java:275)
at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556)
... 5 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.entity.EntityClientPlayerMP
at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
... 32 more
Caused by: java.lang.NullPointerException
at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
... 34 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
Minecraft Version: 1.7.10
Operating System: Linux (i386) version 3.19.0-47-generic
Java Version: 1.8.0_73, Oracle Corporation
Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
Memory: 73758440 bytes (70 MB) / 241446912 bytes (230 MB) up to 259522560 bytes (247 MB)
JVM Flags: 0 total; 
AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1558 39 mods loaded, 39 mods active
States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
UCH mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
UCH FML{7.10.99.99} [Forge Mod Loader](forge.jar) 
UCH Forge{10.13.4.1558} [Minecraft Forge](forge.jar) 
UCH CodeChickenCore{1.0.2.9} [CodeChicken Core](minecraft.jar) 
UCH Micdoodlecore{} [Micdoodle8 Core](minecraft.jar) 
UCH <CoFH ASM>{000} [CoFH ASM](minecraft.jar) 
UCH bdlib{1.9.4.109} [BD Lib](bdlib-1.9.4.109-mc1.7.10.jar) 
UCH qmunitylib{1.0} [QmunityLib](QmunityLib-1.7.10-0.1.114-universal.jar) 
UCH bluepower{0.2.962} [Blue Power](BluePower-1.7.10-0.2.962-universal.jar) 
UCH CoFHCore{1.7.10R3.1.0} [CoFH Core](CoFHCore-[1.7.10]3.1.0-323.jar) 
UCH BuildCraft|Core{7.0.21} [BuildCraft](buildcraft-7.0.21.jar) 
UCH BuildCraft|Silicon{7.0.21} [BC Silicon](buildcraft-7.0.21.jar) 
UCH BuildCraft|Factory{7.0.21} [BC Factory](buildcraft-7.0.21.jar) 
UCH BuildCraft|Builders{7.0.21} [BC Builders](buildcraft-7.0.21.jar) 
UCH BuildCraft|Energy{7.0.21} [BC Energy](buildcraft-7.0.21.jar) 
UCH BuildCraft|Robotics{7.0.21} [BC Robotics](buildcraft-7.0.21.jar) 
UCH BuildCraft|Transport{7.0.21} [BC Transport](buildcraft-7.0.21.jar) 
UCH GalacticraftCore{3.0.12} [Galacticraft Core](GalacticraftCore-1.7-3.0.12.437.jar) 
UCH GalacticraftMars{3.0.12} [Galacticraft Planets](Galacticraft-Planets-1.7-3.0.12.437.jar) 
UCE GalaxySpace{1.0.6} [GalaxySpace](GalaxySpace-1.0.6+STABLE.jar) 
UCH iChunUtil{4.2.2} [iChunUtil](iChunUtil-4.2.2.jar) 
UCH GraviGun{4.0.0-beta} [GraviGun](GravityGun-4.0.0-beta.jar) 
UCH headcrumbs{1.7.0} [Headcrumbs](Headcrumbs-1.7.0.jar) 
UCH IronChest{6.0.62.742} [Iron Chest](ironchest-1.7.10-6.0.62.742-universal.jar) 
UCH Mantle{1.7.10-0.3.2.jenkins184} [Mantle](Mantle-1.7.10-0.3.2.jar) 
UCH ForgeMultipart{1.1.2.331} [Forge Multipart](ForgeMultipart-1.7.10-1.1.2.331-universal.jar) 
UCH Mekanism{8.1.8} [Mekanism](Mekanism-1.7.10-8.1.8.258.jar) 
UCH MekanismGenerators{8.1.8} [MekanismGenerators](MekanismGenerators-1.7.10-8.1.8.258.jar) 
UCH MekanismTools{8.1.8} [MekanismTools](MekanismTools-1.7.10-8.1.8.258.jar) 
UCH MrTJPCoreMod{1.1.0.32} [MrTJPCore](MrTJPCore-1.1.0.32-universal.jar) 
UCH NetherOres{1.7.10R2.3.1} [Nether Ores](NetherOres-[1.7.10]2.3.1-22.jar) 
UCH projectbench{0.5.0} [Project Bench Updated](ProjectBench-Update-1.7.10-0.5.jar) 
UCH ProjectE{1.7.10-PE1.9.4} [ProjectE](ProjectE-1.7.10-PE1.9.4.jar) 
UCH ThermalFoundation{1.7.10R1.2.2} [Thermal Foundation](ThermalFoundation-[1.7.10]1.2.2-111.jar) 
UCH ThermalExpansion{1.7.10R4.1.1} [Thermal Expansion](ThermalExpansion-[1.7.10]4.1.1-237.jar) 
UCH TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct](TConstruct-1.7.10-1.8.8.jar) 
UCH McMultipart{1.1.2.331} [Minecraft Multipart Plugin](ForgeMultipart-1.7.10-1.1.2.331-universal.jar) 
UCH aobd{2.8.4} [Another One Bites The Dust](AOBD-2.8.4.jar) 
UCH ForgeMicroblock{1.1.2.331} [Forge Microblocks](ForgeMultipart-1.7.10-1.1.2.331-universal.jar) 
CoFHCore: -[1.7.10]3.1.0-323
Mantle Environment: Environment healthy.
NetherOres: -[1.7.10]2.3.1-22
ThermalFoundation: -[1.7.10]1.2.2-111
ThermalExpansion: -[1.7.10]4.1.1-237
TConstruct Environment: Environment healthy.
List of loaded APIs: 
- Baubles|API (1.0.1.10) from ThermalFoundation-[1.7.10]1.2.2-111.jar
- bluepowerAPI (1.0) from BluePower-1.7.10-0.2.962-universal.jar
- BuildCraftAPI|blocks (1.0) from buildcraft-7.0.21.jar
- BuildCraftAPI|blueprints (1.3) from buildcraft-7.0.21.jar
- BuildCraftAPI|boards (2.0) from buildcraft-7.0.21.jar
- BuildCraftAPI|core (1.5) from buildcraft-7.0.21.jar
- BuildCraftAPI|crops (1.1) from buildcraft-7.0.21.jar
- BuildCraftAPI|events (1.0) from buildcraft-7.0.21.jar
- BuildCraftAPI|facades (1.1) from buildcraft-7.0.21.jar
- BuildCraftAPI|filler (4.0) from buildcraft-7.0.21.jar
- BuildCraftAPI|fuels (2.0) from buildcraft-7.0.21.jar
- BuildCraftAPI|gates (4.1) from buildcraft-7.0.21.jar
- BuildCraftAPI|items (1.1) from buildcraft-7.0.21.jar
- BuildCraftAPI|library (2.0) from buildcraft-7.0.21.jar
- BuildCraftAPI|power (1.3) from buildcraft-7.0.21.jar
- BuildCraftAPI|recipes (3.0) from buildcraft-7.0.21.jar
- BuildCraftAPI|robotics (2.1) from buildcraft-7.0.21.jar
- BuildCraftAPI|statements (1.1) from buildcraft-7.0.21.jar
- BuildCraftAPI|tablet (1.0) from buildcraft-7.0.21.jar
- BuildCraftAPI|tiles (1.2) from buildcraft-7.0.21.jar
- BuildCraftAPI|tools (1.0) from buildcraft-7.0.21.jar
- BuildCraftAPI|transport (4.1) from buildcraft-7.0.21.jar
- CoFHAPI (1.7.10R1.0.13B2) from CoFHLib-[1.7.10]1.1.1-181.jar
- CoFHAPI|block (1.7.10R1.0.13B2) from CoFHLib-[1.7.10]1.1.1-181.jar
- CoFHAPI|core (1.7.10R1.0.13B2) from CoFHLib-[1.7.10]1.1.1-181.jar
- CoFHAPI|energy (1.7.10R1.0.1) from buildcraft-7.0.21.jar
- CoFHAPI|fluid (1.7.10R1.0.13B2) from CoFHLib-[1.7.10]1.1.1-181.jar
- CoFHAPI|inventory (1.7.10R1.0.13B2) from CoFHLib-[1.7.10]1.1.1-181.jar
- CoFHAPI|item (1.7.10R1.1.0) from CoFHCore-[1.7.10]3.1.0-323.jar
- CoFHAPI|modhelpers (1.7.10R1.0.13B2) from CoFHLib-[1.7.10]1.1.1-181.jar
- CoFHAPI|tileentity (1.7.10R1.1.0) from CoFHCore-[1.7.10]3.1.0-323.jar
- CoFHAPI|transport (1.7.10R1.1.0) from CoFHCore-[1.7.10]3.1.0-323.jar
- CoFHAPI|world (1.7.10R1.1.0) from CoFHCore-[1.7.10]3.1.0-323.jar
- CoFHLib (1.7.10R1.0.3B3) from CoFHLib-[1.7.10]1.1.1-181.jar
- CoFHLib|audio (1.7.10R1.0.3B3) from CoFHLib-[1.7.10]1.1.1-181.jar
- CoFHLib|gui (1.7.10R1.0.3B3) from CoFHLib-[1.7.10]1.1.1-181.jar
- CoFHLib|gui|container (1.7.10R1.1.1) from CoFHCore-[1.7.10]3.1.0-323.jar
- CoFHLib|gui|element (1.7.10R1.1.1) from CoFHCore-[1.7.10]3.1.0-323.jar
- CoFHLib|gui|element|listbox (1.7.10R1.0.3B3) from CoFHLib-[1.7.10]1.1.1-181.jar
- CoFHLib|gui|slot (1.7.10R1.0.3B3) from CoFHLib-[1.7.10]1.1.1-181.jar
- CoFHLib|inventory (1.7.10R1.0.3B3) from CoFHLib-[1.7.10]1.1.1-181.jar
- CoFHLib|render (1.7.10R1.1.1) from CoFHCore-[1.7.10]3.1.0-323.jar
- CoFHLib|render|particle (1.7.10R1.0.3B3) from CoFHLib-[1.7.10]1.1.1-181.jar
- CoFHLib|util (1.7.10R1.0.3B3) from CoFHLib-[1.7.10]1.1.1-181.jar
- CoFHLib|util|helpers (1.7.10R1.0.3B3) from CoFHLib-[1.7.10]1.1.1-181.jar
- CoFHLib|util|position (1.7.10R1.1.1) from CoFHCore-[1.7.10]3.1.0-323.jar
- CoFHLib|world (1.7.10R1.1.1) from CoFHCore-[1.7.10]3.1.0-323.jar
- CoFHLib|world|feature (1.7.10R1.0.3B3) from CoFHLib-[1.7.10]1.1.1-181.jar
- Galacticraft API (1.0) from GalacticraftCore-1.7-3.0.12.437.jar
- MekanismAPI|core (8.0.0) from Mekanism-1.7.10-8.1.8.258.jar
- MekanismAPI|energy (8.0.0) from Mekanism-1.7.10-8.1.8.258.jar
- MekanismAPI|gas (8.0.0) from Mekanism-1.7.10-8.1.8.258.jar
- MekanismAPI|infuse (8.0.0) from Mekanism-1.7.10-8.1.8.258.jar
- MekanismAPI|laser (8.0.0) from Mekanism-1.7.10-8.1.8.258.jar
- MekanismAPI|reactor (8.0.0) from Mekanism-1.7.10-8.1.8.258.jar
- MekanismAPI|recipe (8.0.0) from Mekanism-1.7.10-8.1.8.258.jar
- MekanismAPI|transmitter (8.0.0) from Mekanism-1.7.10-8.1.8.258.jar
- MekanismAPI|util (8.0.0) from Mekanism-1.7.10-8.1.8.258.jar
- ProjectEAPI (7) from ProjectE-1.7.10-PE1.9.4.jar
  Profiler Position: N/A (disabled)
  Is Modded: Definitely; Server brand changed to 'fml,forge'
  Type: Dedicated Server (map_server.txt)`

**Comment by BlesseNtumble** [comment]
Fix crash on server in 1.0.6: https://yadi.sk/d/-ssrX4P4oWuoL
