### ISSUE TITLE
Crash of galaxy space in loading 

### ISSUE THREAD

**Issue by Regidix** [BlesseNtumble/GalaxySpace#605]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: 1.12.2
2. Galacticraft version: 4.0.2.280
3. GalaxySpace version: 2.0.1.9
4. AsmodeusCore version (for 2.0.1 version and above): 0.0.30
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): SSP
6. Other add-ons: 
------------------------------------------------------------------------
While the game is loading the game crashes and show a mistake code in the minecraft launcher, this is happened to me when i upgrade to the latest version of galaxyspace, on old versions works fine.
When crash the game shows this crash report:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.280.jar)
  GSHooksLoader (GalaxySpace-1.12.2-2.0.19.jar)
  ShutdownPatcher (mcef-1.12.2-1.11b-coremod.jar)
Contact their authors BEFORE contacting forge

// You should try our sister game, Minceraft!

Time: 7/20/22 5:06 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from GalaxySpace (galaxyspace)
Caused by: java.lang.NoSuchFieldError: SATELLITE
	at galaxyspace.systems.SolarSystem.SolarSystemBodies.registrycelestial(SolarSystemBodies.java:561)
	at galaxyspace.systems.SolarSystem.SolarSystemBodies.postInit(SolarSystemBodies.java:749)
	at galaxyspace.GalaxySpace.postInit(GalaxySpace.java:223)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:754)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 362698296 bytes (345 MB) / 973078528 bytes (928 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2855 Optifine OptiFine_1.12.2_HD_U_G6_pre1 17 mods loaded, 17 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                  | Version       | Source                                       | Signature                                |
	|:----- |:------------------- |:------------- |:-------------------------------------------- |:---------------------------------------- |
	| LCHIJ | minecraft           | 1.12.2        | minecraft.jar                                | None                                     |
	| LCHIJ | mcp                 | 9.42          | minecraft.jar                                | None                                     |
	| LCHIJ | FML                 | 8.0.99.99     | forge-1.12.2-14.23.5.2855.jar                | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJ | forge               | 14.23.5.2855  | forge-1.12.2-14.23.5.2855.jar                | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJ | micdoodlecore       |               | minecraft.jar                                | None                                     |
	| LCHIJ | galacticraftcore    | 4.0.2.280     | GalacticraftCore-1.12.2-4.0.2.280.jar        | None                                     |
	| LCHIJ | galacticraftplanets | 4.0.2.280     | Galacticraft-Planets-1.12.2-4.0.2.280.jar    | None                                     |
	| LCHIJ | asmodeuscore        | 0.0.30        | AsmodeusCore-1.12.2-0.0.30.jar               | None                                     |
	| LCHIJ | extendedrenderer    | v1.0          | coroutil-1.12.1-1.2.37.jar                   | None                                     |
	| LCHIJ | coroutil            | 1.12.1-1.2.37 | coroutil-1.12.1-1.2.37.jar                   | None                                     |
	| LCHIJ | configmod           | v1.0          | coroutil-1.12.1-1.2.37.jar                   | None                                     |
	| LCHIE | galaxyspace         | 2.0.19        | GalaxySpace-1.12.2-2.0.19.jar                | None                                     |
	| LCHI  | jei                 | 4.16.1.301    | jei_1.12.2-4.16.1.301 (2).jar                | None                                     |
	| LCHI  | mcef                | 1.11          | mcef-1.12.2-1.11b.jar                        | None                                     |
	| LCHI  | mjrlegendslib       | 1.12.2-1.2.1  | MJRLegendsLib-1.12.2-1.2.1.jar               | b02331787272ec3515ebe63ecdeea0d746653468 |
	| LCHI  | webdisplays         | 1.1           | webdisplays-1.12.2-1.1.jar                   | None                                     |
	| LCHI  | worldedit           | 6.1.10        | worldedit-forge-mc1.12.2-6.1.10-dist (1).jar | None                                     |

	Loaded coremods (and transformers): 
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.280.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
GSHooksLoader (GalaxySpace-1.12.2-2.0.19.jar)
  galaxyspace.core.hooklib.minecraft.PrimaryClassTransformer
ShutdownPatcher (mcef-1.12.2-1.11b-coremod.jar)
  net.montoyo.mcef.coremod.ShutdownPatcher
	GL info: ' Vendor: 'Intel' Version: '4.6.0 - Build 26.20.100.7323' Renderer: 'Intel(R) UHD Graphics 620'
	OptiFine Version: OptiFine_1.12.2_HD_U_G6_pre1
	OptiFine Build: 20210323-161358
	Render Distance Chunks: 6
	Mipmaps: 1
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 - Build 26.20.100.7323
	OpenGlRenderer: Intel(R) UHD Graphics 620
	OpenGlVendor: Intel
	CpuCount: 4

------------------------------------------------------------------------
Screenshot/Video:
![image](https://user-images.githubusercontent.com/102194821/180094177-62fc8fd3-8afb-4515-8e1a-5b71b7934ff1.png)

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):

[latest.log](https://github.com/BlesseNtumble/GalaxySpace/files/9154881/latest.log)

------------------------------------------------------------------------

**Comment by ppfirework** [comment]
i have the same problem

**Comment by BlesseNtumble** [comment]
Update AsmodeusCore and Galacticraft to 284 build (Galacticraft Legacy on CurseForge)
