### ISSUE TITLE
minecraft crashes

### ISSUE THREAD

**Issue by TwixKiss** [BlesseNtumble/GalaxySpace#627]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: 1.12.2
2. Galacticraft version: 4.0.2.280
3. GalaxySpace version:  2.0.14 
4. AsmodeusCore version (for 2.0.1 version and above): 0.0.30
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)):ssp
6. Other add-ons: [1.12.2]bspkrscore-universal-8.0.1   [1.12]TreeCapitator-client-1.43.0  Advanced+Machines-61.0.0  Advanced+Solar+Panels-4.3.0  appliedenergistics2-rv6-stable-7 AsmodeusCore-1.12.2-0.0.30  Baubles-1.12-1.5.2  BetterBuildersWands-1.12.2-0.13.2.271+5997513 Bookshelf-1.12.2-2.3.590  BrandonsCore-1.12.2-2.4.20.162-universal  Clumps-3.1.2 CodeChickenLib-1.12.2-3.2.3.358-universal  CoFHCore-1.12.2-4.6.6.1-universal  CoFHWorld-1.12.2-1.4.0.1-universal Draconic-Evolution-1.12.2-2.3.25.351-universal  EnchantingPlus-1.12.2-5.0.176 EnchantmentDescriptions-1.12.2-1.1.15  forestry_1.12.2-5.8.2.422
GalacticraftCore-1.12.2-4.0.2.280  Galacticraft-Planets-1.12.2-4.0.2.280  gravestone-1.10.3  Gravitation+Suite-3.1.1  Hwyla-1.8.26-B41_1.12.2  ido-1.12.2-1.1.0  industrialcraft-2-2.8.170-ex112  InventoryTweaks-1.63  ironchest-1.12.2-7.0.72.847  jei_1.12.2-4.16.1.302  journeymap-1.12.2-5.7.1  MicdoodleCore-1.12.2-4.0.2.280 RedstoneFlux-1.12-2.1.1.1-universal   SmoothFont-mc1.12.2-2.1
------------------------------------------------------------------------  
Description of the issue:
 When you start the game, the game crashes

------------------------------------------------------------------------
Screenshot/Video:
-

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):
---- Minecraft Crash Report ----

WARNING: coremods are present:
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  CorePlugin (SmoothFont-mc1.12.2-2.1.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.280.jar)
  GSHooksLoader (GalaxySpace-1.12.2-2.0.14.jar)
Contact their authors BEFORE contacting forge

// There are four lights!

Time: 9/3/22 4:33 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from GalaxySpace (galaxyspace)
Caused by: java.lang.NoClassDefFoundError: galaxyspace/systems/SolarSystem/planets/asteroids/dimension/sky/SkyProviderAsteroids
	at galaxyspace.core.proxy.ClientProxy.preload(ClientProxy.java:141)
	at galaxyspace.GalaxySpace.preInit(GalaxySpace.java:181)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: galaxyspace.systems.SolarSystem.planets.asteroids.dimension.sky.SkyProviderAsteroids
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 42 more
Caused by: java.lang.NoClassDefFoundError: asmodeuscore/core/astronomy/sky/SkyProviderBaseOld
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 44 more
Caused by: java.lang.ClassNotFoundException: asmodeuscore.core.astronomy.sky.SkyProviderBaseOld
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 48 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1217841240 bytes (1161 MB) / 2449473536 bytes (2336 MB) up to 2684354560 bytes (2560 MB)
	JVM Flags: 12 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:+ParallelRefProcEnabled -Xms2048M -Xmx2560M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2860 Optifine OptiFine_1.12.2_HD_U_G5 42 mods loaded, 42 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                    | Version                  | Source                                             | Signature                                |
	|:----- |:--------------------- |:------------------------ |:-------------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft             | 1.12.2                   | minecraft.jar                                      | None                                     |
	| LCH   | mcp                   | 9.42                     | minecraft.jar                                      | None                                     |
	| LCH   | FML                   | 8.0.99.99                | forge-1.12.2-14.23.5.2860.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge                 | 14.23.5.2860             | forge-1.12.2-14.23.5.2860.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | micdoodlecore         |                          | minecraft.jar                                      | None                                     |
	| LCH   | smoothfontcore        | mc1.12.2-2.1             | minecraft.jar                                      | None                                     |
	| LCH   | smoothfont            | mc1.12.2-2.1             | SmoothFont-mc1.12.2-2.1.jar                        | None                                     |
	| LCH   | bspkrscore            | 8.0.0                    | [1.12.2]bspkrscore-universal-8.0.1.jar             | None                                     |
	| LCH   | treecapitator         | 1.43.0                   | [1.12]TreeCapitator-client-1.43.0.jar              | None                                     |
	| LCH   | ic2                   | 2.8.170-ex112            | industrialcraft-2-2.8.170-ex112.jar                | de041f9f6187debbc77034a344134053277aa3b0 |
	| LCH   | advanced_machines     | 61.0.0                   | Advanced+Machines-61.0.0.jar                       | None                                     |
	| LCH   | advanced_solar_panels | 4.3.0                    | Advanced+Solar+Panels-4.3.0.jar                    | None                                     |
	| LCH   | appliedenergistics2   | rv6-stable-7             | appliedenergistics2-rv6-stable-7.jar               | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
	| LCH   | galacticraftcore      | 4.0.2.280                | GalacticraftCore-1.12.2-4.0.2.280.jar              | None                                     |
	| LCH   | galacticraftplanets   | 4.0.2.280                | Galacticraft-Planets-1.12.2-4.0.2.280.jar          | None                                     |
	| LCH   | asmodeuscore          | 0.0.30                   | AsmodeusCore-1.12.2-0.0.30.jar                     | None                                     |
	| LCH   | baubles               | 1.5.2                    | Baubles-1.12-1.5.2.jar                             | None                                     |
	| LCH   | betterbuilderswands   | 0.13.2                   | BetterBuildersWands-1.12.2-0.13.2.271+5997513.jar  | None                                     |
	| LCH   | bookshelf             | 2.3.590                  | Bookshelf-1.12.2-2.3.590.jar                       | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | codechickenlib        | 3.2.3.358                | CodeChickenLib-1.12.2-3.2.3.358-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCH   | redstoneflux          | 2.1.1                    | RedstoneFlux-1.12-2.1.1.1-universal.jar            | None                                     |
	| LCH   | brandonscore          | 2.4.20                   | BrandonsCore-1.12.2-2.4.20.162-universal.jar       | None                                     |
	| LCH   | clumps                | 3.1.2                    | Clumps-3.1.2.jar                                   | None                                     |
	| LCH   | cofhcore              | 4.6.6                    | CoFHCore-1.12.2-4.6.6.1-universal.jar              | None                                     |
	| LCH   | cofhworld             | 1.4.0                    | CoFHWorld-1.12.2-1.4.0.1-universal.jar             | None                                     |
	| LCH   | thermalfoundation     | 2.6.7                    | ThermalFoundation-1.12.2-2.6.7.1-universal.jar     | None                                     |
	| LCH   | draconicevolution     | 2.3.25                   | Draconic-Evolution-1.12.2-2.3.25.351-universal.jar | None                                     |
	| LCH   | eplus                 | 5.0.176                  | EnchantingPlus-1.12.2-5.0.176.jar                  | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | enchdesc              | 1.1.15                   | EnchantmentDescriptions-1.12.2-1.1.15.jar          | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | jei                   | 4.16.1.302               | jei_1.12.2-4.16.1.302.jar                          | None                                     |
	| LCH   | forestry              | 5.8.2.422                | forestry_1.12.2-5.8.2.422.jar                      | None                                     |
	| LCE   | galaxyspace           | 2.0.14                   | GalaxySpace-1.12.2-2.0.14.jar                      | None                                     |
	| LC    | gravestone            | 1.10.3                   | gravestone-1.10.3.jar                              | None                                     |
	| LC    | gravisuite            | 3.1.1                    | Gravitation+Suite-3.1.1.jar                        | None                                     |
	| LC    | waila                 | 1.8.26                   | Hwyla-1.8.26-B41_1.12.2.jar                        | None                                     |
	| LC    | ido                   | 1.0.6                    | ido-1.12.2-1.1.0.jar                               | None                                     |
	| LC    | inventorytweaks       | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                           | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LC    | ironchest             | 1.12.2-7.0.67.844        | ironchest-1.12.2-7.0.72.847.jar                    | None                                     |
	| LC    | journeymap            | 1.12.2-5.7.1             | journeymap-1.12.2-5.7.1.jar                        | None                                     |
	| LC    | thaumcraft            | 6.1.BETA26               | Thaumcraft-1.12.2-6.1.BETA26.jar                   | None                                     |
	| LC    | thermalexpansion      | 5.5.7                    | ThermalExpansion-1.12.2-5.5.7.1-universal.jar      | None                                     |
	| LC    | thermaldynamics       | 2.5.6                    | ThermalDynamics-1.12.2-2.5.6.1-universal.jar       | None                                     |

	Loaded coremods (and transformers): 
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
CorePlugin (SmoothFont-mc1.12.2-2.1.jar)
  bre.smoothfont.asm.Transformer
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.280.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
GSHooksLoader (GalaxySpace-1.12.2-2.0.14.jar)
  galaxyspace.core.hooklib.minecraft.PrimaryClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 457.63' Renderer: 'GeForce 920MX/PCIe/SSE2'
	AE2 Version: stable rv6-stable-7 for Forge 14.23.5.2768
	OptiFine Version: OptiFine_1.12.2_HD_U_G5
	OptiFine Build: 20210124-142939
	Render Distance Chunks: 7
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 457.63
	OpenGlRenderer: GeForce 920MX/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

------------------------------------------------------------------------

**Comment by BlesseNtumble** [comment]
Update GalaxySpace

**Comment by ghost** [comment]
Make sure all your mods are up to date.
