### ISSUE TITLE
opening the assembly machines crashes the game

### ISSUE THREAD

**Issue by Lotemn** [BlesseNtumble/GalaxySpace#672]
**Do not remove this template, without it your issue will not be considered!**

**Please fill in the form below:**
------------------------------------------------------------------------
1. Minecraft version: 1.12.2
2. Galacticraft version: 1.12.2-4.0.6
3. GalaxySpace version: 1.12.2-2.1.1
4. AsmodeusCore version (for 2.0.1 version and above): 1.0.0
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): SSP
6. Other add-ons:
------------------------------------------------------------------------
Description of the issue:
opening the assembly table crashes the game

------------------------------------------------------------------------
Screenshot/Video:

https://github.com/BlesseNtumble/GalaxySpace/assets/143113876/2cf1a63c-3c9c-4937-b219-0a7e3e0353c0

------------------------------------------------------------------------
Attached log file (or url on pastebin.com):

---- Minecraft Crash Report ----

WARNING: coremods are present:
  GSHooksLoader (GalaxySpace-1.12.2-2.1.1.jar)
  MicdoodlePlugin (Galacticraft-1.12.2-4.0.6.jar)
Contact their authors BEFORE contacting forge

// Why did you do that?

Time: 8/26/23 12:00 PM
Description: Unexpected error

java.lang.IllegalAccessError: tried to access field net.minecraft.inventory.InventoryCrafting.field_70465_c from class galaxyspace.systems.SolarSystem.planets.overworld.inventory.ContainerAssembler
	at galaxyspace.systems.SolarSystem.planets.overworld.inventory.ContainerAssembler.<init>(ContainerAssembler.java:24)
	at galaxyspace.systems.SolarSystem.planets.overworld.gui.GuiAssembler.<init>(GuiAssembler.java:29)
	at galaxyspace.core.handler.GSGuiHandler.getClientGuiElement(GSGuiHandler.java:201)
	at galaxyspace.core.handler.GSGuiHandler.getClientGuiElement(GSGuiHandler.java:178)
	at net.minecraftforge.fml.common.network.NetworkRegistry.getLocalGuiContainer(NetworkRegistry.java:276)
	at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:111)
	at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2550)
	at galaxyspace.systems.SolarSystem.planets.overworld.blocks.machines.BlockAssembler.onMachineActivated(BlockAssembler.java:48)
	at micdoodle8.mods.galacticraft.core.blocks.BlockAdvanced.func_180639_a(BlockAdvanced.java:65)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:423)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1579)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2254)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2020)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1808)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at galaxyspace.systems.SolarSystem.planets.overworld.inventory.ContainerAssembler.<init>(ContainerAssembler.java:24)
	at galaxyspace.systems.SolarSystem.planets.overworld.gui.GuiAssembler.<init>(GuiAssembler.java:29)
	at galaxyspace.core.handler.GSGuiHandler.getClientGuiElement(GSGuiHandler.java:201)
	at galaxyspace.core.handler.GSGuiHandler.getClientGuiElement(GSGuiHandler.java:178)
	at net.minecraftforge.fml.common.network.NetworkRegistry.getLocalGuiContainer(NetworkRegistry.java:276)
	at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:111)
	at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2550)
	at galaxyspace.systems.SolarSystem.planets.overworld.blocks.machines.BlockAssembler.onMachineActivated(BlockAssembler.java:48)
	at micdoodle8.mods.galacticraft.core.blocks.BlockAdvanced.func_180639_a(BlockAdvanced.java:65)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:423)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1579)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2254)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2020)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [GCEntityClientPlayerMP['Lotemn'/352, l='MpServer', x=-220.96, y=72.00, z=98.92]]
	Chunk stats: MultiplayerChunkCache: 574, 574
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-188,64,112), Chunk: (at 4,4,0 in -12,7; contains blocks -192,0,112 to -177,255,127), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 944 game time, 944 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false

------------------------------------------------------------------------

**Comment by BlesseNtumble** [comment]
Downgrade GC Legacy. In 4.0.4 version work fine

**Comment by ROMVoid95** [comment]
So is this caused by GC or not?

**Comment by DonnerTechQ2** [comment]
> Downgrade GC Legacy. In 4.0.4 version work fine

Will there ever be a fix?
