### ISSUE TITLE
Внезапный краш (просто гулял по миру)

### ISSUE THREAD

**Issue by ruslan-tyshchenko** [BlesseNtumble/GalaxySpace#68]
Гулял по ОБЫЧНОМУ миру, и тадам - краш. Перезахожу - снова краш. И так вcегда на конкретных чанках).
Kcauldron. 1.7.10.  
Galaxy Space 1.0.9. Galacticraft версии из вашей ссылки вк.

`---- Minecraft Crash Report ----
// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 20.06.16 16:42
Description: Unexpected error

java.lang.ArrayIndexOutOfBoundsException: 1
    at galaxyspace.BarnardsSystem.planets.barnardaC.blocks.BarnardaCBlockPlanks.func_149691_a(BarnardaCBlockPlanks.java:82)
    at net.minecraft.block.Block.func_149673_e(Block.java:556)
    at net.minecraft.client.renderer.RenderBlocks.func_147793_a(RenderBlocks.java:9361)
    at net.minecraft.client.renderer.RenderBlocks.func_147751_a(RenderBlocks.java:5061)
    at net.minecraft.client.renderer.RenderBlocks.func_147784_q(RenderBlocks.java:4712)
    at net.minecraft.client.renderer.RenderBlocks.func_147805_b(RenderBlocks.java:307)
    at net.minecraft.client.renderer.WorldRenderer.func_147892_a(WorldRenderer.java:320)
    at net.minecraft.client.renderer.RenderGlobal.func_72716_a(RenderGlobal.java:2232)
    at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1514)
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1305)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at D.W.run(D/W)
    at java.lang.Thread.run(Unknown Source)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at galaxyspace.BarnardsSystem.planets.barnardaC.blocks.BarnardaCBlockPlanks.func_149691_a(BarnardaCBlockPlanks.java:82)
    at net.minecraft.block.Block.func_149673_e(Block.java:556)
    at net.minecraft.client.renderer.RenderBlocks.func_147793_a(RenderBlocks.java:9361)
    at net.minecraft.client.renderer.RenderBlocks.func_147751_a(RenderBlocks.java:5061)
    at net.minecraft.client.renderer.RenderBlocks.func_147784_q(RenderBlocks.java:4712)
    at net.minecraft.client.renderer.RenderBlocks.func_147805_b(RenderBlocks.java:307)
    at net.minecraft.client.renderer.WorldRenderer.func_147892_a(WorldRenderer.java:320)
    at net.minecraft.client.renderer.RenderGlobal.func_72716_a(RenderGlobal.java:2232)
    at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1514)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [GCEntityClientPlayerMP['nanorus'/503784, l='MpServer', x=-499,63, y=84,62, z=1400,81]]
    Chunk stats: MultiplayerChunkCache: 49, 49
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: World: (-84,77,567), Chunk: (at 12,4,7 in -6,35; contains blocks -96,0,560 to -81,255,575), Region: (-1,1; contains chunks -32,32 to -1,63, blocks -512,0,512 to -1,255,1023)
    Level time: 121173607 game time, 541397 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
    Forced entities: 6 total; [GCEntityClientPlayerMP['nanorus'/503784, l='MpServer', x=-499,63, y=84,62, z=1400,81], EntitySlime['Слизень'/505295, l='MpServer', x=-456,67, y=68,00, z=1362,26], EntityScarecrow['Пугало'/503789, l='MpServer', x=-458,13, y=80,00, z=1434,56], EntityPig['Свинья'/503788, l='MpServer', x=-454,31, y=42,00, z=1416,44], EntityTier1Rocket['Ракета 1-го уровня'/503787, l='MpServer', x=-468,50, y=94,90, z=1435,50], EntityMooshroom['Мууухомор'/503786, l='MpServer', x=-477,34, y=86,00, z=1432,47]]
    Retry entities: 0 total; []
    Server brand: kcauldron,cauldron,craftbukkit,mcpc,fml,forge
    Server type: Non-integrated multiplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:927)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at D.W.run(D/W)
    at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_92, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 205970688 bytes (196 MB) / 677904384 bytes (646 MB) up to 954728448 bytes (910 MB)
    JVM Flags: 2 total; -Xmx1024m -XX:MaxPermSize=128m
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 15, tallocated: 95
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 Optifine OptiFine_1.7.10_HD_U_C1 56 mods loaded, 56 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJA  mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJA  FML{7.10.99.99} [Forge Mod Loader](forge-1.7.10-10.13.4.1614-1.7.10-universal_jar) 
    UCHIJA  Forge{10.13.4.1614} [Minecraft Forge](forge-1.7.10-10.13.4.1614-1.7.10-universal_jar) 
    UCHIJA  appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core](minecraft.jar) 
    UCHIJA  CodeChickenCore{1.0.7.47} [CodeChicken Core](minecraft.jar) 
    UCHIJA  Micdoodlecore{} [Micdoodle8 Core](minecraft.jar) 
    UCHIJA  NotEnoughItems{1.0.5.118} [Not Enough Items](NotEnoughItems-1.7.10-1.0.5.118-universal.jar) 
    UCHIJA  optifinerus{1.0} [rusOptifine](OptifineRUS.jar) 
    UCHIJA  ChocoPatcher{1.2} [Choco Patcher](minecraft.jar) 
    UCHIJA  <CoFH ASM>{000} [CoFH ASM](minecraft.jar) 
    UCHIJA  bspkrsCore{6.16} [bspkrsCore]([1.7.10]bspkrsCore-universal-6.16.jar) 
    UCHIJA  IC2{2.2.820-experimental} [IndustrialCraft 2](industrialcraft-2-2.2.820-experimental-client.jar) 
    UCHIJA  AdvancedSolarPanel{1.7.10-3.5.1} [Advanced Solar Panels](AdvancedSolarPanel-1.7.10-3.5.1.jar) 
    UCHIJA  appliedenergistics2{rv2-stable-10} [Applied Energistics 2](appliedenergistics2-rv2-stable-10-client.jar) 
    UCHIJA  ArmorStatusHUD{1.28} [ArmorStatusHUD](ArmorStatusHUD-client-1.28.jar) 
    UCHIJA  CoFHCore{1.7.10R3.1.2} [CoFH Core](CoFHCore-[1.7.10]3.1.2-325.jar) 
    UCHIJA  BuildCraft|Core{7.1.16} [BuildCraft](buildcraft-7.1.16-client.jar) 
    UCHIJA  BuildCraft|Builders{7.1.16} [BC Builders](buildcraft-7.1.16-client.jar) 
    UCHIJA  BuildCraft|Transport{7.1.16} [BC Transport](buildcraft-7.1.16-client.jar) 
    UCHIJA  BuildCraft|Energy{7.1.16} [BC Energy](buildcraft-7.1.16-client.jar) 
    UCHIJA  BuildCraft|Silicon{7.1.16} [BC Silicon](buildcraft-7.1.16-client.jar) 
    UCHIJA  BuildCraft|Robotics{7.1.16} [BC Robotics](buildcraft-7.1.16-client.jar) 
    UCHIJA  BuildCraft|Factory{7.1.16} [BC Factory](buildcraft-7.1.16-client.jar) 
    UCHIJA  ExtrabiomesXL{3.16.4} [ExtrabiomesXL](extrabiomesxl_1.7.10-3.16.4.jar) 
    UCHIJA  Forestry{4.2.2.50} [Forestry for Minecraft](forestry_1.7.10-4.2.2.50.jar) 
    UCHIJA  Baubles{1.0.1.10} [Baubles](Baubles-1.7.10-1.0.1.10.jar) 
    UCHIJA  ThermalFoundation{1.7.10R1.2.3} [Thermal Foundation](ThermalFoundation-[1.7.10]1.2.3-112.jar) 
    UCHIJA  ThermalExpansion{1.7.10R4.1.2} [Thermal Expansion](ThermalExpansion-[1.7.10]4.1.2-240.jar) 
    UCHIJA  BuildCraft|Compat{7.1.1} [BuildCraft Compat](buildcraft-compat-7.1.1.jar) 
    UCHIJA  CarpentersBlocks{3.3.5} [Carpenter's Blocks](CarpenterBlocks-v3.3.5.jar) 
    UCHIJA  endercore{1.7.10-0.0.1.13_alpha} [EnderCore](EnderCore-1.7.10-0.0.1.13_alpha.jar) 
    UCHIJA  GalacticraftCore{3.0.12} [Galacticraft Core](GalacticraftCore-1.7-3.0.12.454.jar) 
    UCHIJA  GalacticraftMars{3.0.12} [Galacticraft Planets](Galacticraft-Planets-1.7-3.0.12.454.jar) 
    UCHIJA  GalaxySpace{1.0.9} [GalaxySpace](GalaxySpace-1.0.9 STABLE.jar) 
    UCHIJA  GraviSuite{1.7.10-2.0.3} [Graviation Suite](GraviSuite-1.7.10-2.0.3-client.jar) 
    UCHIJA  inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks](InventoryTweaks-1.59-dev-152.jar) 
    UCHIJA  IronChest{6.0.60.741} [Iron Chest](ironchest-1.7.10-6.0.60.741-universal.jar) 
    UCHIJA  MineTweaker3{3.0.10} [MineTweaker 3](MineTweaker3-1.7.10-3.0.10B.jar) 
    UCHIJA  cfm{3.4.7} [�9MrCrayfish's Furniture Mod](MrCrayfishFurnitureMod-v3.4.7.jar) 
    UCHIJA  NEIAddons{1.12.14.40} [NEI Addons](neiaddons-1.12.14.40-mc1.7.10.jar) 
    UCHIJA  NEIAddons|Developer{1.12.14.40} [NEI Addons: Developer Tools](neiaddons-1.12.14.40-mc1.7.10.jar) 
    UCHIJA  NEIAddons|AppEng{1.12.14.40} [NEI Addons: Applied Energistics 2](neiaddons-1.12.14.40-mc1.7.10.jar) 
    UCHIJA  NEIAddons|Botany{1.12.14.40} [NEI Addons: Botany](neiaddons-1.12.14.40-mc1.7.10.jar) 
    UCHIJA  NEIAddons|Forestry{1.12.14.40} [NEI Addons: Forestry](neiaddons-1.12.14.40-mc1.7.10.jar) 
    UCHIJA  NEIAddons|CraftingTables{1.12.14.40} [NEI Addons: Crafting Tables](neiaddons-1.12.14.40-mc1.7.10.jar) 
    UCHIJA  NEIAddons|ExNihilo{1.12.14.40} [NEI Addons: Ex Nihilo](neiaddons-1.12.14.40-mc1.7.10.jar) 
    UCHIJA  neiintegration{1.1.2} [NEI Integration](NEIIntegration-MC1.7.10-1.1.2.jar) 
    UCHIJA  Treecapitator{1.7.10} [Treecapitator](Treecapitator-universal-2.0.4.jar) 
    UCHIJA  Waila{1.5.10} [Waila](Waila-1.5.10_1.7.10.jar) 
    UCHIJA  WailaHarvestability{1.1.2} [Waila Harvestability](WailaHarvestability-mc1.7.x-1.1.2.jar) 
    UCHIJA  wailaplugins{MC1.7.10-0.2.0-23} [WAILA Plugins](WAILAPlugins-MC1.7.10-0.2.0-23.jar) 
    UCHIJA  WaslieCore{1.1} [WaslieCore](WaslieCore-1.1-universal.jar) 
    UCHIJA  wawla{1.3.3} [What Are We Looking At](Wawla-1.3.3-1.7.10.jar) 
    UCHIJA  worldedit{6.1.1-SNAPSHOT} [WorldEdit](worldedit-forge-mc1.7.10-6.1.1-SNAPSHOT-dist.jar) 
    UCHIJA  worldedit-cui{1.0} [WorldEdit Client User Interface](WorldEditCUI-1.7.10-1.0.0.jar) 
    UCHIJA  MouseTweaks{2.4.4} [Mouse Tweaks](MouseTweaks-2.4.4-mc1.7.10.jar) 
    AE2 Version: stable rv2-stable-10 for Forge 10.13.2.1291
    CoFHCore: -[1.7.10]3.1.2-325
    ThermalFoundation: -[1.7.10]1.2.3-112
    ThermalExpansion: -[1.7.10]4.1.2-240
    Forestry : Warning: You have mods that change the behavior of Minecraft, ForgeModLoader, and/or Minecraft Forge to your client: 
Optifine
These may have caused this error, and may not be supported. Try reproducing the crash WITHOUT these mods, and report it then.
    AE2 Integration: IC2:ON, RotaryCraft:OFF, RC:OFF, BC:ON, RF:ON, RFItem:ON, MFR:OFF, DSU:ON, FZ:OFF, FMP:OFF, RB:OFF, CLApi:OFF, Waila:ON, InvTweaks:ON, NEI:ON, CraftGuide:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF
    Launched Version: 1.7.10
    LWJGL: 2.9.3
    OpenGL: AMD Radeon R7 200 Series GL version 4.5.13431 Compatibility Profile Context 16.150.2211.0, ATI Technologies Inc.
    GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

```
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: [WorldMario_1.zip]
Current Language: Русский (Россия)
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Anisotropic Filtering: Off (1)`
```

**Comment by BlesseNtumble** [comment]
И постоянно так?

**Comment by ruslan-tyshchenko** [comment]
Каждые минут 15-30 у каждого игрока.

**Comment by BlesseNtumble** [comment]
Пока попробуйте отключить систему Барнарды в конфиге.
Я проверю у себя.

**Comment by ruslan-tyshchenko** [comment]
Отключаю. В случае следующего краша - отпишусь.
